### ISSUE TITLE
a new NewRelic account_id is not considered with an existing tfstate that was executed against different account_id

### ISSUE THREAD

**Issue by tabartels** [newrelic/terraform-provider-newrelic#1019]
### Terraform Version
0.12.20

### Affected Resource(s)
at least the following, but I assume most if not all are affected:
- `newrelic_alert_policy`
- `newrelic_nrql_alert_condition`

### Terraform Configuration
```
cat providers.tf
provider "newrelic" {
  version = "2.13.3"
  region = "US"
}

cat prom-nr-policy.tf
resource "newrelic_alert_policy" "prom_alert" {
  name                = "${var.cluster_name}.${var.environment} alerts"
  incident_preference = "PER_CONDITION_AND_TARGET"
}

resource "newrelic_alert_policy_channel" "email" {
  policy_id = newrelic_alert_policy.prom_alert.id
  channel_ids = [
    data.newrelic_alert_channel.email.id
  ]
}

resource "newrelic_alert_policy_channel" "slack" {
  policy_id = newrelic_alert_policy.prom_alert.id
  channel_ids = [
    data.newrelic_alert_channel.slack.id
  ]
}

cat prom-nrql-alerts.tf
resource "newrelic_nrql_alert_condition" "prom_pod_unhealthy" {
  policy_id            = newrelic_alert_policy.prom_alert.id
  name                 = "${var.cluster_name}.${var.environment} Prometheus Pods Unhealthy"
  enabled              = true
  violation_time_limit = "THIRTY_DAYS"

  fill_option           = "last_value"
  expiration_duration   = "780"
  open_violation_on_expiration = true
  close_violations_on_expiration = true

  critical {
    threshold_duration    = 600
    operator              = "below"
    threshold             = 1
    threshold_occurrences = "all"
  }

  nrql {
    query       = "SELECT min(isReady) FROM K8sPodSample WHERE namespace = 'monitoring' AND label.app = 'prometheus' AND clusterName = '${var.cluster_fqdn}'"
    evaluation_offset = 3
  }

  value_function = "single_value"
}
```

### Actual Behavior
When switching the account ID (for testing, switch from a production NewRelic account ID to a sandbox ephemeral account ID), the TF code seems to dismiss the account ID provided via either environment variables (NEW_RELIC_ACCOUNT_ID) or specifying the account ID in the provider configuration block. TF will execute against the previous account ID as can be seen in the TFstate file (each resource does have an attribute `account_id`).
See below snippet from state file (account ID redacted)
```
{
      "mode": "managed",
      "type": "newrelic_alert_policy",
      "name": "prom_alert",
      "provider": "provider.newrelic",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "account_id": redacted,

{
      "mode": "managed",
      "type": "newrelic_nrql_alert_condition",
      "name": "prom_pod_unhealthy",
      "provider": "provider.newrelic",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "account_id": redacted,
```

### Expected Behavior
NewRelic Terraform provider should detect that there is a new account ID provided and dismiss the account ID from the previous run in the TFstate file.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. have NewRelic TF config and point it to account A via env var `NEW_RELIC_ACCOUNT_ID`
2. `terraform apply`
3. Change account ID to account B
4. `terraform apply`
5. confirm that terraform still executes against account A
6. drop TFstate file
7. `terraform init` & `terraform apply`
8. confirm that terraform now executes against account B

### Debug Output
There is no failure produced by Terraform, it just executes against the previously set NewRelic account ID and if no changes other than that, plan output provides no changes and exits as usual.

### Important Factoids
Nothing special really

**Comment by zlesnr** [comment]
Hi, thank you for raising the issue.  I would certainly guess that switching account IDs would break TF in some way, since the IDs of each resource are tied to an account.  What is the behavior you are expecting in more detail?  Should we remove the resources from the state file, so that they get re-created when you switch back to the old account?  Is switching the account something you expect to do once, or are you expecting to be able to flip back and forth between accounts?

**Comment by tabartels** [comment]
I think it's indeed an edge case, definitely not flipping back and forth between accounts on an ongoing basis. 
But I would have expected, since NEW_RELIC_ACCOUNT_ID is an input variable, that it will be considered as such. So if I provide (on purpose) a different account ID, that Terraform plan would inform me about the changes (as you described, remove the resources from the state file and create new ones) and the apply would create the resources in the new account. It took me some time to figure out that TF code was executed against the existing account, which I didn't expect.

**Comment by zlesnr** [comment]
I'll look at the code more closely here in a few, but I'm still unclear what we would do with the old resources.  In the case where resources exist for the old account ID, should they be destroyed automatically and then recreated in new account?  That seems like it could be unexpected for the case that you mention, where you want to take the production code and run it in staging.  Deleting all of the production resources and then recreating them in staging doesn't sound like the right approach to me.  Leaving dangling and unmanaged resource in production also doesn't sound like a great experience, since, if you wanted to go back to production, the state file would have lost the information about which resources were under management create new ones, which would mean duplicates.

**Comment by tabartels** [comment]
I see your point Zach, and it's a very valid one. At a minimum I think the provider should give a warning message that it detected a change in NewRelic account_id compared to the previous execution, and suggest how to tackle that situation instead (e.g. take a backup of the previous state file and generate a new state file for the other account).
