### ISSUE TITLE
Handle data source entity naming conventions more elequently

### ISSUE THREAD

**Issue by jpvajda** [newrelic/terraform-provider-newrelic#1058]
Relates to #1041

### Issue

What's happening here when an app is named the same in 2 different accounts , but the newrelic_entity data source is not yet defaulting its account_id from the provider config. The API is returning 2 applications and the provider is just grabbing the first one; Given that Entity search is meant to be cross-account, this behavior may be hard to understand at first glance by a user. 

### current work around 

You should be able to specify your account ID in the newrelic_entity data source's config with the accountId attribute to uniquely identify your application.

### Considerations

1. it looks like we don't have account_id plumbed in as a search parameter and It's just a computed attribute. This is one approach to resolve this problem. We could provide an explicit accountID search param, or update the docs to show how to use tags to search in specific accounts.

3. Better error messaging would be helpful: We could fail when we get more than 1 entity back in a search, with a message to the user to be more specific in their search.

4. We can document more effectively how to handle this case with the current limitations. I think updating the docs to show how to filter by account and erroring if more than one result is found is what we should do

**Comment by casey-robertson** [comment]
If this isn't related I can delete but I maybe be seeing this in a config a I set up today (we do pass accountId in our query because I ran into this issue months ago when setting up our code).

This is our code (which is Pulumi but is essentially Terraform-by-proxy):

```
// Get the entity ID
		if (newRelicOpts.entityName) {
			const entity = pulumi.output(
				newrelic.getEntity({
					name: newRelicOpts.entityName,
					domain: newRelicOpts.entityDomain,
					tag: {
						key: 'accountId',
						value: `${newRelicOpts.accountID}`
					}
				})
			);
```

Seems like no matter what name I put in, I get:

```
Error: invocation of newrelic:index/getEntity:getEntity returned an error: invoking newrelic:index/getEntity:getEntity: the name 'xxxxxxxxx' does not match any New Relic One entity for the given search parameters
```

I've tried both the display name and the reporting name that shows up in APM to no avail.  What's the best way to find those via the console?  And If I provide you with our account number and the app name would that help?  Thanks!

**Comment by jpvajda** [comment]
@casey-robertson it seems related to this feature for sure. If you wanted us to take a look at this, could you file a seperate issue and drop a comment with a link to the new issue on Github? - Thanks!

**Comment by jthurman42** [comment]
Few thoughts:

1. It would be difficult to do the first consideration, as how could you UNSET the account ID if you did not want to default to the provider.  This would force using account_id even with unique names.
2. This would be a breaking change, unless we raised a warning instead of an error.
3. Current documentation does show filtering by accountId tag, so unless the multiple-match error is a requirement, this would be met for completion.
