### ISSUE TITLE
Insights API End of Life and the impact on “newrelic_dashboard”

### ISSUE THREAD

**Issue by kidk** [newrelic/terraform-provider-newrelic#1297]
The New Relic Insights UI and API has served New Relic users well for over five years, digging into their data and creating dashboards on both web and mobile. The release of New Relic One in May 2019 introduced a new dashboarding solution based on the New Relic One platform: faster, more responsive, and more flexible.

And those dashboard capabilities in New Relic One have only been getting better since then. More and more features have been added to reach feature parity with Insights. And since the release of New Relic One dashboards we have been able to introduce features Insights couldn’t support well, like:

- [Facet linking](https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/filter-new-relic-one-dashboards-facets)
- [Facet linking with support for Cases](https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/filter-new-relic-one-dashboards-facets#facet-linking-cases)
- [Dashboards with Pages(Data Apps in Insights](https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard#add-pages)
- [TV Mode & Page Cycle](https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard)
- [Multiple Queries per widget](https://docs.newrelic.com/docs/query-your-data/explore-query-data/query-builder/use-advanced-nrql-mode-query-data)
- [Data Explorer for Events, Metrics and TimeSlices](https://docs.newrelic.com/docs/query-your-data/explore-query-data/explore-data/introduction-data-explorer)
- [Any many more to come](https://newrelic.com/blog/how-to-relic/dashboards-and-custom-visualizations)

As engineers, we know that all software eventually reaches the end of its useful life, and that time is upon us for New Relic Insights and its API's. This means that on the 28th of July the “newrelic_dashboard” resource in the New Relic Terraform provider will stop working. All existing “newrelic_dashboard” resources should be migrated to the new “newrelic_one_dashboard” resource. 

To prevent issues with your Terraform provider:
- Upgrade to v2.x of the New Relic Terraform Provider. This [migration guide](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v2) will help you configure the upgrade.
- Move your dashboards to the newrelic_one_dashboard resource from the old resource. To assist with this transition New Relic will provide a guide and solution to export HCL templates from an existing New Relic dashboard. You can find the latest of the guide [here](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_newrelic_dashboard).

As always, we’re here to help. If you have any questions, doubts or remarks don’t hesitate to respond to this ticket or reach out to your New Relic representative.

**Comment by jpvajda** [comment]
Great recap issue, I've pinned it so it's highly visible here:  https://github.com/newrelic/terraform-provider-newrelic/issues

**Comment by wshao12** [comment]
HI support, we are using 2.x, but still got error: 
provider "newrelic" {
  account_id    = var.account_id
  admin_api_key = var.admin_api_key
  api_key       = var.api_key
  region        = var.region
  version       = "~> 2.22.1"
}
terraform {
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
    }
  }
  required_version = "0.13.6"
}

Ran Apply for project: newrelic-prod-dashboards-engagement dir: prod/dashboards/engagement workspace: default
Apply Error
exit status 1: running "tf-apply" in "/home/atlantis/.atlantis/repos/seismic/terraform-newrelic/851/default/prod/dashboards/engagement": 
newrelic_one_dashboard.prod: Modifying... [id=NDcyMTQzfFZJWnxEQVNIQk9BUkR8OTQxMDI0]
Error: A downstream error occurred., [{"extensions":{},"message":"Operation on dashboard entity failed with guid:NDcyMTQzfFZJWnxEQVNIQk9BUkR8OTQxMDI0 with cause: Error 500 calling Insights with url https://insights-api.service.nr-ops.net/rpm_api/1/accounts/472143/dashboards/941024: Internal Server Error; "}]
  on engagement.tf line 1, in resource "newrelic_one_dashboard" "prod":
   1: resource "newrelic_one_dashboard" "prod" {

One thing I noticed is, https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_v2
IN this migration guide, api key format needs to be changes. but we did not. Could this be the root cause of the error?

**Comment by kidk** [comment]
@wshao12 I'm not sure why this is happening. Could you create a separate issue and include the relevant terraform code?
