### ISSUE TITLE
new_relic_one_dashboard cannot be updated/changed

### ISSUE THREAD

**Issue by blakeroberts-wk** [newrelic/terraform-provider-newrelic#1358]
## Please include the following with your bug report

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version

```
$ terraform -v
Terraform v0.15.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.46.0
+ provider registry.terraform.io/newrelic/newrelic v2.23.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_one_dashboard`

### Terraform Configuration

```hcl
terraform {
  backend "s3" {
    bucket         = "..."
    key            = "..."
    region         = "..."
    dynamodb_table = "..."
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.6"
    }
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.23.0"
    }
  }
}
```

### Actual Behavior
When trying to update a preexisting new relic one dashboard, the changes aren't actually applied even though the terraform apply command completes successfully. The changes aren't applied to the New Relic resource or the terraform backend state storage file.

### Expected Behavior
The resource is updated.

### Steps to Reproduce
1. `terraform apply`
  - And type yes
2. `terraform apply`
  - And notice that the changes applied in 1 are seen in the output of 2

### Debug Output

I will link a support ticket with the attached file: https://support.newrelic.com/tickets/460939/edit

**Comment by Gene5ive** [comment]
Whoever takes this - ping me in Slack and I will send you the logs.

**Comment by rconto** [comment]
The same problem has been reported by a company I'm doing a pilot with right now. They successfully create a dashboard with "public read-only" rights using TR. All the following updates made by the same user are not being applied in NR but TR doesn't report any error, i.e., TR thinks they successfully completed. This company is in the EU domain and has users configured with OKTA/SSO, in case this is important.

**Comment by Julien4218** [comment]
FYI, I've been able to repro this issue.
If the new dashboard contains a widget having a NRQL syntax error, the apply indicates "success", however the deployment failed because of the widget nrql syntax error.
Creating a new dashboard with the same content shows the syntax error during a create.

**Comment by tomdeering-wf** [comment]
@Julien4218 here's your bug. [`resourceNewRelicOneDashboardUpdate calls `DashboardUpdate`](https://github.com/newrelic/terraform-provider-newrelic/blob/723581c0a38a4194a193d6ac8e92cd80e990da31/newrelic/resource_newrelic_one_dashboard.go#L451), whose response  [contains a slice of `Errors`](https://github.com/newrelic/newrelic-client-go/blob/e2683ce4d772299e090e27b9a0825ed54d39f1cf/pkg/dashboards/types.go#L283). But those errors are never checked, so the update appears to succeed even though it failed with an error.

Compare that to your [`resourceNewRelicOneDashboardCreate` function](https://github.com/newrelic/terraform-provider-newrelic/blob/723581c0a38a4194a193d6ac8e92cd80e990da31/newrelic/resource_newrelic_one_dashboard.go#L394), that actually checks the errors on the response. That's why invalid NRQL errors are surfaced by terraform when creating dashboards, but not when updating them.

**Comment by blakeroberts-wk** [comment]
bump

**Comment by aelmekeev** [comment]
I believe I've tracked down at least two issues:
1. Silent fail due to `public_read_only` and the apply run with an API key different from the user that created the dashboard.
2. Looks like widgets inside the page needs to be sorted in alphabetical order otherwise we would see change in the plan over and over again.
