### ISSUE TITLE
newrelic_alert_channel: payload_string values are contunially considered to be modified if the attributes are not ordered alphabetically

### ISSUE THREAD

**Issue by jsbnr** [newrelic/terraform-provider-newrelic#1367]
I found a bug/peculiarity with the `newrelic_alert_channel` resource. If you use a JSON payload via `payload_string` then the JSON object is re-ordered somewhere (maybe by NR API's). This means if you provide an object with the attributes _not in alphabetical order_ then the resource continually re-applies and gets recreated on every apply. 

I fixed by issue temporarily by making sure the attributes in my terraform object were in the same order as returned by the API's (alphabetically ordered).

### Terraform Version
Terraform 15.5.5, Provider version 2.23.0

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_alert_channel`

### Terraform Configuration
This code will continually re-create as "b" comes before "a" and the returned object from New Relic will be re-ordered a,b,c.

```hcl
resource "newrelic_alert_channel" "example" {
    ...
    payload_string = <<EOF
    {
        "b": "b",
        "a": "a",
        "c": "c"
    }
    EOF
    ...
}

```

### Actual Behavior
The resource wants to destroy and re-create on every apply.

### Expected Behavior
The resource should not be modified as the configuration is exaclty the same.

### Steps to Reproduce
Provide a JSON object as the `payload_string` with attributes out of order.

**Comment by jsbnr** [comment]
Please dont go stale :)

**Comment by MAN98** [comment]
Our workaround for this issue is to order it based on the channel_id of the alert channel. That will remove the noise in tf plan/apply.

**Comment by emetcalf9** [comment]
I was able to reproduce and found that the `payload_string` is being converted to a map and loaded in as `payload` when creating the channel. Due to the way Go handles json marshaling, keys are alphabetized when the stored map is converted back to a string representation. If the keys in your payload string are not alphabetized the provider will see this as a different value that will need to be updated. Ensuring your payload_string keys are alphabetized should prevent the payload_string from being destroyed and recreated, so long as they haven't changed.

We recommend using this workaround to avoid having your channels deleted and recreated on every apply because Alert channels are scheduled to be deprecated and replaced with "Destinations" in the next year: https://discuss.newrelic.com/t/big-news-for-alerts-and-applied-intelligence/161436
