### ISSUE TITLE
Validation error on nrql monitor

### ISSUE THREAD

**Issue by aujjwal-smarsh** [newrelic/terraform-provider-newrelic#1508]
Terraform version: 0.13.0
NewRelic provider: 2.21.0

Error: 
```
Validation Error

on modules/alerts/nrql_monitor/main.tf line 1, in resource "newrelic_nrql_alert_condition" "simple_nrql_monitor_condition":

1: resource "newrelic_nrql_alert_condition" "simple_nrql_monitor_condition" {
```
I am not sure but it might be because of the NRQL query. Is SINCE not allowed?
```
NRQL module:

module "xyz_test_rate" {

    source = "../modules/alerts/nrql_monitor"

    app_name = "xyz"

    app_prefix = "xyz"

    condition_name = "xyz"

    policy_id = module.xyz.xyz
    enabled = "true"

    nrql_expression = "SELECT SUM(NUMERIC(count)) FROM xyzAPI where spaceName='xyz-prod' AND metricName='xyz.xyz.xyz' and status='xyz' since 60 minutes ago FACET status"

    operator = "below"

    threshold = "12345"

}
```

**Comment by baNROne** [comment]
NRQL conditions [do not allow](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition#nrql) the use of `SINCE`. Please see the [provider documentation](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition) for details on configuring `threshold_duration` and `aggregation_window` for NRQL conditions.

**Comment by baNROne** [comment]
I want to add that this type of question would fit better in our [Developer Community](https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit), where other New Relic users are asking questions and discussing their experiences with the New Relic Terraform provider. You may find your question has already been answered there.

**Comment by aujjwal-smarsh** [comment]
Thanks @baNROne  for the info
