### ISSUE TITLE
Cross account channel creation fails

### ISSUE THREAD

**Issue by Alex-Boza** [newrelic/terraform-provider-newrelic#1645]
We are provisioning sub-accounts programatically. Goal is to add some alert policies, conditions, channels after the account has been created as a baseline. We wish to achieve this using Terraform and USER API key created in the Master account. This is where things get ugly and we run into an error below:

│ Error: 422 response returned: There was an error. Unable to add channel IDs: [5965566].
│
│   with newrelic_alert_policy_channel.foo,
│   on main.tf line 71, in resource "newrelic_alert_policy_channel" "foo":
│   71: resource "newrelic_alert_policy_channel" "foo" {

**The issue:**

- Policy gets created in the sub-account
- Conditions get created in sub-account
- Channel gets created in the Master account (in the above example, the channel ID [5965566])
- Channel can’t be linked to the policy since it sits in the Master account

**Expectation:**

- Policy gets created in the sub-account
- Conditions get created in the sub-account
- Channel gets created in the sub-account
- Channel is linked to the policy (in the sub-account)

**Comment by benohara** [comment]
We also see this.  Any chance of a quick fix?

**Comment by MrColeC** [comment]
We are also running into this. I saw in #840 
```text
The channels API gets its account id from the API key. Cross account channel management is not available at this time. 
```

Which is very unfortunate news. That behavior is not expected and is inconsistent with how the rest of the APIs function (they take their Account ID from the Terraform declared account id).

**Comment by MrColeC** [comment]
A co-worker walked the code backwards and found out that the REST v2 endpoint is being used by the NR Terraform Provider and that this ask would allow it to support declaring the Account ID instead of inferring it.

https://github.com/newrelic/newrelic-client-go/issues/697

**Comment by TechIsCool** [comment]
Walking this down working with @MrColeC
1. The Terraform Provider depends on https://github.com/newrelic/newrelic-client-go/
2. The Terraform provider for [create](https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/resource_newrelic_alert_policy_channel.go#L82-L112) calls [UpdatePolicyChannelsWithContext](https://github.com/newrelic/newrelic-client-go/blob/main/pkg/alerts/policy_channels.go#L19-L41)
2. Due to the fact that this go client still uses the rest API for these calls it does not automatically get the account_id defined. 3. There is a open issue on seen here https://github.com/newrelic/newrelic-client-go/issues/697 that mentions adding a header for this to work. Work would have to be done on the client and then on the provider for this to function but sounds possible.

**Comment by kidk** [comment]
This is indeed the last part of our alert pipeline that needs to be moved to the new API. The reason why we haven't done so is because the notification channels are going away in the future, and we're releasing a new method in the next couple of months. 

Once the new method is available we will implement it in the Terraform provider, and create a migration guide for any existing notification channels. We'll do our best to keep the disruption to a minimum.

We always take care not to implement functionality that will go away in the near future. We want to keep our Terraform provider as stable as possible, which means sometimes we end up in this position. 

Thanks for your understanding.

**Comment by Fallenstedt** [comment]
I have chatted with @jthurman42 to see how we can best add X-Account-ID header in our New Relic Go client. I will start working on this and provide an update when a pull request is ready. 

We may need two PRs, one for the newrelic go client and the other for the terraform provider, to make cross account channel creation work well.
