### ISSUE TITLE
Terraform v0.11.13 and New Relic Provided V2.27.1 not compatible?

### ISSUE THREAD

**Issue by sabareshrengarajan** [newrelic/terraform-provider-newrelic#1653]
Hi there,
Terraform Version **Terraform v0.11.13**
New Relic Provider Version : 2.27.1 (To enable streaming methods update in the nrql alerts)

Issue: We are using Terraform 0.11x and current New relic provider version is 2.22.1. The terraform Plan and apply works perfectly fine. Now New Relic has changed the evaluation_offset and have recommended to use Streaming methods instead and that support is available only from NR provider version 2.27.1. If I update the provider version to 2.27.1 in my terraform code and run terraform init -> It initialises successfully.
Terraform Plan. Fails with the below error

Error: provider.newrelic: Incompatible API version with plugin. Plugin version: 5, Core version: 4

The documentation claims that v2.27.1 support 0.11x version of Terraform we are unable to run it in the environment. We have a huge list of terraform code which needs to be upgraded so, upgrading terraform is not an option at the moment. Is there a work around for this? also the NR provider should be backward compatible as well ?

**Comment by kidk** [comment]
Hi @sabareshrengarajan 

That's correct, latest versions of the provider won't work with 0.11x because of the Terraform SDK EOL. 

https://discuss.hashicorp.com/t/end-of-life-timeline-for-v1-of-the-terraform-plugin-sdk/24991

We would advice to upgrade to the latest versions of Terraform and the New Relic provider as we cannot make promises that older versions will keep working. In general New Relic and Terraform will support versions up to 2 years after their release. 

I've added a task for us to make this more clear in the documentation.

**Comment by sabareshrengarajan** [comment]
@kidk  thank you for the reply, Is there no work around other than upgrading terraform? We have lots and lots of modules to be updated before we use the latest version of terrafom and this is not something planned and have to be thought through as it might have implications on the day to day releases in our environment?

**Comment by kidk** [comment]
@sabareshrengarajan I don't think so. I would advise to upgrade now, as you are many major versions behind, and the problem will only get worse over time. 

The new versions of Terraform and the New Relic provider will also provide lots of bugfixes and improvements.

**Comment by kidk** [comment]
I'll close this ticket as there's nothing we can do. 

Just FYI there's an EOL coming up for all old versions of the New Relic terraform provider: https://github.com/newrelic/terraform-provider-newrelic/issues/1665
