### ISSUE TITLE
Duplicated policies alert terraform NR version 2.39.2

### ISSUE THREAD

**Issue by jjan123** [newrelic/terraform-provider-newrelic#1742]
**Terraform Version**
```
 newrelic = {
      source  = "newrelic/newrelic"
      version = ">= 2.39.2"
    }
```

**Affected Resource(s)**
newrelic_alert_policy

**Actual Behavior**
If we run this code below:

```
resource "newrelic_alert_policy" "policy1" {
  name                = "myAlert1"
  incident_preference = "PER_CONDITION_AND_TARGET"
}

resource "newrelic_alert_policy" "policy2" {
  name                = "myAlert1"
  incident_preference = "PER_CONDITION_AND_TARGET"
}
```
we will get duplicated "myAlert1" policies.

**Expected Behavior**
What should have happened?
I would expect the code to not create the duplicated "myAlert1" policies. should it be smart enough to know that "myAlert1" already exist and if it already exists, do not create another "myAlert1" policy.

**Steps to Reproduce**
Please list the steps required to reproduce the issue, for example:

terraform plan and apply the following code

```
resource "newrelic_alert_policy" "policy1" {
  name                = "myAlert1"
  incident_preference = "PER_CONDITION_AND_TARGET"
}

resource "newrelic_alert_policy" "policy2" {
  name                = "myAlert1"
  incident_preference = "PER_CONDITION_AND_TARGET"
}
```

![image](https://user-images.githubusercontent.com/64254300/161619962-9a41a4c6-d0db-4d26-8496-0f00cda578e2.png)

**Comment by kidk** [comment]
Hi @jjan123 

This is expected behaviour for Terraform. When creating policies we check on the ID of the policy, and not the name. In general most providers will check on some sort of unique ID, and not a unique name. 

If you want to re-use an existing policy you can use import: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_policy#import

At the moment we don't have any plans to change this.

Hope this helps
