### ISSUE TITLE
Better Logging Capabilities for New Relic Terraform Provider

### ISSUE THREAD

**Issue by aravind-bigfish** [newrelic/terraform-provider-newrelic#1774]
### Feature Description
Hello Team,

When working with Terraform, i'm noticing some of the errors whether its syntactical related, such as using an incorrect NRQL, we are getting allot of "Unavailable desc = transport is closing" related errors. One issue we faced was when we created alert conditions & policies, when we ran the workspaces for certain environments, they succeeded, however some failed. They were both using the same New Relic Apis; we were using version the newrelic TF provider version 2.23.0. When i updated to the latest, the errors went away and the terraform plans/applies succeeded. It would be great to get better visibility into errors, warnings such as using a deprecated version would be nice to have. 

### Describe Alternatives
The Alternative is to just update to the latest new relic terraform provider version, however there should be logging in place which is more responsive as to what the issue is.

### Additional context
Add any other context here.

**Comment by kidk** [comment]
The recommended solution will always be to use the latest version of our provider as it contains the latest features, and more importantly bug fixes. We don't provide any support for older versions of the provider, mostly because the API Terraform uses has a constant rate of small changes we need to implement. 

We could look at adding a message that your provider is outdated, but I would need to discuss with the team to see if that's a possibility. 

I'm going to close this ticket for now as there's no action we can take at this time. You should still be able to respond if needed.
