### ISSUE TITLE
Logs data source

### ISSUE THREAD

**Issue by somatorio** [newrelic/terraform-provider-newrelic#2030]
### Feature Description
A data source for logs, in some cases (mine was for Cloudflare logpush to New Relic ownership challenge) you need to get the content of a log file from New Relic so you can use that content as input for a module (or resource even)

### Describe Alternatives
What I had to do as a (hopefully temporary) work around was to use https://registry.terraform.io/providers/hashicorp/http/ to make a request directly to New Relic API and then get the response, process it and then pass the output to the resource needing that content, which was messy and "hacky"

**Comment by kidk** [comment]
Thanks for the suggestion @somatorio I think this is very similar to #1787 as logs are available as NRQL. 

I'm going to leave this open as there might be a different solution to this, but I'd also watch the other thread.

**Comment by somatorio** [comment]
Oh yeah, I think this would work as well :)
I'll also the other thread

**Comment by pranav-new-relic** [comment]
Hi @somatorio, since all resources in the Terraform Provider  mostly communicate with NerdGraph or REST APIs, the most probable solution to this would be via an NRQL query that would fetch logs, as suggested in the previous comment. Given other key priorities (across projects too), we don't have an ETA for this, but whenever possible, we'd probably want to take this up as a NRQL query-fetching data source in #1787 . Closing this issue for us to be able to better keep an eye on active issues - thank you for reporting :)
