### ISSUE TITLE
Unable to create workflows with email destination using Terraform

### ISSUE THREAD

**Issue by mukul-gupta1** [newrelic/terraform-provider-newrelic#2032]
I'm using terraform to create workflows for email destinations but the workflow is not able to find workflow notification channels ID.
I have copied the same code and executed it from this link (https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/workflow#full-scenario-example).
PFA the attachments of the code and error. Removed Account ID and emails ID.
<img width="677" alt="Screenshot_2" src="https://user-images.githubusercontent.com/112538344/192949405-6c715933-5e42-42ed-b681-a76ec298a46a.png">
 
[newrelic_tf_bug.txt](https://github.com/newrelic/terraform-provider-newrelic/files/9671407/newrelic_tf_bug.txt)

**Comment by gutsul** [comment]
@mukul-gupta1 Look to this [solution](https://github.com/newrelic/terraform-provider-newrelic/issues/1974).

**Comment by mukul-gupta1** [comment]
It should have mentioned somewhere that we need to use IINT instead of other values.
@gutsul

**Comment by gutsul** [comment]
@mukul-gupta1 It's already mentioned in the [doc](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_channel#:~:text=product%20%3D%20%22IINT%22%20//%20(Workflows)).

**Comment by mukul-gupta1** [comment]
Hi @gutsul ,
Thanks for the response. However, updating ERROR_TRACKING to IINT works for the email, but there is still an issue in the plugin. After running it a few times getting below error 
 ### notification channelResponse.Entities response is empty
which leads to a plugin crash.

**Comment by maryal-iag** [comment]
Also running into same issue. Resource creation works fine after changing it to IINT, but subsequent plan/apply throws the following error: [ERROR] notification channelResponse.Entities response is empty

![image](https://user-images.githubusercontent.com/109131951/193951548-b53d509f-c47e-4784-b3eb-084b79b9b01f.png)

**Comment by juliostone** [comment]
Has anyone figured it out, I'm having the same problem

**Comment by silanpa** [comment]
Same issues here. Version 3.2.1

![unknown](https://user-images.githubusercontent.com/6666896/194356436-8134ce8a-ed0e-4c32-9c56-53690538db12.png)

**Comment by maryal-iag** [comment]
@silanpa That can be resolved by changing the 'product' property into 'IINT' and once that's resolved you will face the following issue - #2009

**Comment by IliaShurygin** [comment]
@maryal-iag thanks for helping out! 

Regarding https://github.com/newrelic/terraform-provider-newrelic/issues/2009, we are going to address this eventually. For now, I added a workaround you can use in the comments there. 

To sum it up: 
- Please set `product` in the channel resource to `IINT`
  - This is something we will need to clarify in the docs because you are not the first person having this issue
- Please set `account_id` in workflow resource
  - This is a bug on our side, the field should be optional
  - But in the mean time, specifying `account_id` should allow you to create/mange workflows though TF

Please let us know if this works!

**Comment by yoyayoshida** [comment]
I am facing the same error.
In my case, `type` is `"SLACK"` and, `product` and `account_id` are already set to the value @IliaShurygin mentioned above.
Resource creation was well done with Terraform, but below occurs when running `plan` operation with this resource totally unchanged.

```
│ Error: [ERROR] notification channelResponse.Entities response is empty
│ 
│   with newrelic_notification_channel.slack_notification,
│   on notification_channel.tf line 1, in resource "newrelic_notification_channel" "slack_notification":
│    1: resource "newrelic_notification_channel" "slack_notification" {
```

**Comment by IliaShurygin** [comment]
@yoyayoshida this is a different issue 😞 
You can use https://github.com/newrelic/terraform-provider-newrelic/issues/2009 as the tracking ticket for this one

**Comment by mukul-gupta1** [comment]
This issue is different. Its not asking for re-creation its is unable to locate the channel entities.

**Comment by NSSPKrishna** [comment]
Hi @mukul-gupta1, did you upgrade New Relic terraform provider to V 3.5.0?

**Comment by IliaShurygin** [comment]
@mukul-gupta1, the channels issue fix is in review right now, it will most likely be rolled out later this week or sometime the next week.
You could track [the PR](https://github.com/newrelic/terraform-provider-newrelic/pull/2057) if you are blocked by this.

**Comment by IliaShurygin** [comment]
Regarding Slack, there are two ways we are planning to eventually tackle this:
1. See if we can implement it in TF 
2. Implement destination data source so that the import of Slack destinations created through the UI is easier

But our main priority right now is to address the bugs people are currently facing, so I cannot really tell what the ETA for "Slack via TF" feature is.
