### ISSUE TITLE
option to add newrelic_notification_destination ID in newrelic_workflow resource

### ISSUE THREAD

**Issue by vid31** [newrelic/terraform-provider-newrelic#2068]
### Feature Description
As per the [document ](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/workflow) on creating a **newrelic_workflow** resource we are only able to provide a channel ID in the _destination_ argument. 
There should be an option to add the ID of **newrelic_notification_destination**, since channels are going to be deprecated soon and destinations are the correct way going forward.

### Describe Alternatives
I tried adding `newrelic_notification_destination.destination_name.id` to the channel ID argument but that did not work. 
So there are no alternatives as far as I know.

**Comment by IliaShurygin** [comment]
Hi @vid31! 
[Notification channels](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_channel) are not being deprecated, you are probably confusing them with [alert channels](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_channel).

This is not the first time these two are confused, so we clearly have some issues with our documentation (and similar naming does not help either).

[Notification destinations](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_destination) and [notification channels](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_channel) are designed to work together: 
- [Notification destination](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_destination) is a part that contains secrets (credentials/api keys/etc) and some basic details
  -  Generally speaking, you will have one destination per third-party system integration (e.g. one for Slack, one for Jira, etc), with emails being an exception
- A [notification channel](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_channel), on the other hand, is something that contains more specific configuration that is generally not reusable
  - For example, a channel can define a Slack channel name to post notification to, or Jira project to use

The idea behind this separation is to allow people to only configure all integrations once instead of copy-pasting secrets in multiple places.

Alert channels are the our old notification system that is going to eventually be decommissioned and cannot be used with workflows at all, it can only be used with alert policies.

I hope this explanation makes it clear why you generally cannot use destination ID instead of notification channel ID: destination alone is not enough because it does not contain enough information.

We will try to improve our documentation around this topic to avoid future confusion
