### ISSUE TITLE
Synthetic private minion doc(s) need to specify GUID in all places

### ISSUE THREAD

**Issue by npreiser** [newrelic/terraform-provider-newrelic#2072]
Any place in the synthetic resource docs where private minion is used,  including the examples,  please add a note that the "ID" is actually the GUID of the private minion.  
Every minion has multiple ids,  and customers are getting confused.

**Comment by kidk** [comment]
Thanks @npreiser 

We took a look at the documentation and we mention GUID for a lot of the attributes related to private minion. Could you add some detail where exactly you feel we could clear some confusion?

**Comment by ericksoen** [comment]
I ran into the same issue with one of my developers today with the docs for [synthetics private location data source] (https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/synthetics_private_location).

**Comment by NSSPKrishna** [comment]
We have reviewed the documentation and made changes accordingly. Please feel free to raise a new issue if you feel this is still an issue.

**Comment by jayntguru** [comment]
This is still extremely confusing. What's the GUID? How do I match up to what's in the New Relic UI? 

Nothing in this example matches what I can get out of the UI.
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/synthetics_private_location

Or here.
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_monitor#additional-examples

It would be great if the documentation matched something here. Since nothing in the examples match, I don't have a clue what I'm supposed to use here.

account:blah
accountId: blah
key:blah
locationId:foo
minionCount:0
trustedAccountId: foo
verifiedScriptExecution:false
vse:false

Also the terraform plugin will create something that passes an init/plan but errors on apply. (Plan does not seem to be validating the location_private.)

**Comment by jayntguru** [comment]
Couple of other documentation things I found.

https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/synthetics_private_location

The top example here the data name doesn't match what's in the resource example
The bottom example also says  location_private  and it's  locations_private 

I think I figured out how to get the GUID/ID from using data, but I'm confused on how I use multiple locations.
