### ISSUE TITLE
`newrelic_notification_destination` data source should take a name rather than id

### ISSUE THREAD

**Issue by samantha-millar** [newrelic/terraform-provider-newrelic#2270]
Reading the New Relic Terraform provider documentation for the `newrelic_notification_destination` data source, it asks for an ID where it should ask for a name, that then retrieves the ID.

https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/notification_destination

Otherwise `data.newrelic_notification_destination.foo.id` is redundant as the ID can be directly used. 
The ID can change if someone in the account decides to re authenticate which is easy to do.  

I don't want to ask users to get the ID for each slack destination in their sub account as the "copy destination id to clipboard" could easily result in mistaken deletion.
![image](https://user-images.githubusercontent.com/111676727/221993243-f95f41c1-b067-4bcc-9141-ee9261bc13ad.png)

### Actual Behavior

data "newrelic_notification_destination" "foo" {
  id = "1e543419-0c25-456a-9057-fb0eb310e60b"
}

### Expected Behavior

data "newrelic_notification_destination" "foo" {
  name = "slack destination"
}

**Comment by lzaga-newrelic** [comment]
Hi everyone,
We are sorry for your disappointed and we are working on fixing this issue soon.

**Comment by lzaga-newrelic** [comment]
Hi everyone,
A fix for this issue is currently in review: https://github.com/newrelic/terraform-provider-newrelic/pull/2395

**Comment by pranav-new-relic** [comment]
Hi folks - the fix is now out, with the latest version of the Terraform Provider, [v3.25.0](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v3.25.0). The data source now also accepts the name of the destination. You can find more details in the updated documentation of this resource - for instance, this [new example](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/notification_destination#name-example-usage). 

Closing this issue, as the fix is now out. Thank you for reporting this!
cc @lzaga-newrelic
