### ISSUE TITLE
Long execution time while creating Synthetics Monitors

### ISSUE THREAD

**Issue by RizwaanShaik** [newrelic/terraform-provider-newrelic#2322]
We are trying to create simple ping monitors for a private location using terraform newrelic provider but as the number of resources (ping monitors) to create is quite high in number ~ 40k monitors, the execution time is very long (4hrs +) which is leading to timing out of the external job which executes it. 
We want to check if there is an alternate, quicker way to create these simple ping monitors.

Module Configuration
 ```
terraform {
  required_providers {
    newrelic = {
      source = "plugins/newrelic/newrelic"
    }
  }
}

data "newrelic_synthetics_private_location" "private_location" {
  name = var.private_location_name
}

resource "newrelic_synthetics_monitor" "ping_monitor" {
  for_each          = var.monitors
  status            = "ENABLED"
  name              = each.key
  period            = var.period
  uri               = each.value["url"]
  type              = "SIMPLE"
  locations_private = [data.newrelic_synthetics_private_location.private_location.id]

  dynamic "tag" {
    for_each = each.value["tags"]
    content {
      key    = tag.key
      values = [tag.value]
    }
  }
}
```

Terraform version: 1.4.2
NewRelic provider version: 3.17.1

NewRelic support ticket: https://support.newrelic.com/s/case-details?caseId=5008W000013jlMyQAI&isCollaborator=false&followup=false

**Comment by RizwaanShaik** [comment]
Any update on this?

**Comment by pranav-new-relic** [comment]
Hi @RizwaanShaik, we have had a discussion on this issue within our engineering team. We understand that the requirement is to create a very large number of monitors - however, we currently do not have a workaround to achieve this, given the number of monitors needed, for which we do not have an alternate solution to implement from the New Relic Terraform Provider, since this is an issue with Terraform, which is not perfectly optimised for large sets of resources defined in a single configuration. You may see the same has been reported by users using a variety of providers with Terraform, in issues similar to [this](https://github.com/hashicorp/terraform/issues/18981).

At the moment, we'd only be able to suggest you to try modularising your Terraform configuration to be able to split into multiple plans, which we find is a working solution suggested/implemented by a couple of users, in the issue reported above (we'd urge you to have read through the issue for more insights on this). Thanks!

**Comment by RizwaanShaik** [comment]
Hello @pranav-new-relic . Thanks for the response. We'll go ahead with trying to split the workload into multiple plans. 
Closing the issue with this.
