### ISSUE TITLE
Add 'Fit range to data' argument to widget_line page block for newrelic_one_dashboard resource

### ISSUE THREAD

**Issue by pcmangubat** [newrelic/terraform-provider-newrelic#2327]
### Feature Description
Add 'Fit range to data' argument to widget_line page block for newrelic_one_dashboard resource.  Looks like in newrelic_one_dashboard_raw you can set

`        
"yAxisLeft": {         
          "zero": false
  }
`

But newrelic_one_dashboard resource does not have the supported option

### Describe Alternatives
Use newrelic_one_dashboard_raw resource.  But this would need to rework our TF pipelines

**Comment by pranav-new-relic** [comment]
Hi @pcmangubat , thanks for reporting this issue. We are currently working on a similar request - will keep you posted when that is done (ready to be rolled out). Thanks!

**Comment by pranav-new-relic** [comment]
Hi @pcmangubat  - we have released a fix to this issue in the latest version of the Terraform Provider, [v3.21.3](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v3.21.3). A new argument has been added to the schema of `newrelic_one_dashboard` (in line widgets) called `y_axis_left_zero`, which would be a boolean value (true/false), about which you can read more in the updated documentation [here](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#widget_line). This argument would resemble the attribute `"zero"` in the JSON version of the line widget of the dashboard copied from the UI.

Few points about using this new argument -
- Using `y_axis_left_zero = false` would fit the graph to scale. However, if you specify values of  arguments `y_axis_left_min` and `y_axis_left_max` when `y_axis_left_zero = false`, it would override the nature of the graph to be fit to scale, and would eventually render values belonging to the range `y_axis_left_min` - `y_axis_left_max`. This is the case in the UI too - when you try creating a line widget and select "Fit to scale", but specify the minimum and maximum range of values, the fit to scale property is overridden. Hence, **if `y_axis_left_zero` is `false`, `y_axis_left_min` and `y_axis_left_max` are expected not to be specified.**
- Using `y_axis_left_zero = true` would render values in the graph starting from zero to the maximum, as is expected. If `y-axis_left_min` and `y_axis_left_max` are specified with `y_axis_left_zero = true`, values are rendered in the range of the specified minimum and maximum.
- `y_axis_left_zero` is an optional attribute, and would default to `false` if not specified, i.e. the graph would fit to scale unless `y_axis_left_zero = true` is added in the configuration.

Closing this issue as the fix is now live. Thanks for reporting!
