### ISSUE TITLE
Error: INVALID_PARAMETER: Channels ids are already in use by workflows [c47e....

### ISSUE THREAD

**Issue by eunicemetu** [newrelic/terraform-provider-newrelic#2369]
### Terraform Version
Terraform v1.3.9

### Affected Resource(s)
- `newrelic_workflow`

Error:
Error: INVALID_PARAMETER: Channels ids are already in use by workflows [c47ee108-5c11-451e-ba75-2ae4cd37683d, 91a7826f-996a-452e-b316-8bfd64e5b118,...]

Description
The issue is related to the mapping between the workflow and the channel. The error comes while creating the workflow resource.

When running `terraform apply`, it fails on adding the same "notification channel" to some of the "workflows", it says that it is already connected to other workflows. In fact, during the terraform run the channel gets connected to some of the workflows.

Like in the above error it shows that a single channel got connected to 2 workflows but failed for the current workflow.

Actual Behavior

When running "terraform apply":
```

> Error: INVALID_PARAMETER: Channels ids are already in use by workflows [c47ee108-5c11-451e-ba75-2ae4cd37683d, 91a7826f-996a-452e-b316-8bfd64e6h118, 1f336788-3590-4c6d-94g6-586c1fd14930]
> │ 
> │   with module.addons.newrelic_workflow.logop-workflow,
> │   on modules/newrelic/addons/alerts_policies.tf line 184, in resource "newrelic_workflow" "logop-workflow":
> │  184: resource "newrelic_workflow" "logop-workflow" {

```

Expected Behavior

A single channel should get connected to multiple workflows.

Steps to Reproduce

terraform apply

Important Factoids

Manually we are able to create the workflow and attach the same channel which is already connected to other workflows BUT through terraform it fails.

**Comment by pranav-new-relic** [comment]
Hi @eunicemetu - thanks for reporting this issue. We'd probably need a little more info on this to open a conversation with the associated team on this issue - for which we'd like to request you if you can add some more details, such as the Terraform Configuration you've used, Trace Logs (logs obtained when `terraform apply` with `TF_LOG=TRACE`), etc. Thanks!

**Comment by nzur-newrelic** [comment]
Hey @eunicemetu - thanks for writing to us, there seems to be some misunderstanding here.
A single channel should only be connected to a single workflow, that is because if you delete channels in the UI or through Nerdgraph it will delete the channel and in the event the channel is connected to multiple workflows can lead to unclear errors.

I know this is confusing and I apologize for that.
You can find this info under the destination block doc as shown in this [link](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/workflow#nested-destination-blocks)
