### ISSUE TITLE
Implement Update client_secret for azure_link_account

### ISSUE THREAD

**Issue by guineveresaenger** [newrelic/terraform-provider-newrelic#2386]
### Feature Description
azure_link_account [does not currently update the client secret](https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/resource_newrelic_cloud_azure_link_account.go#L147) on Update.
It would be great if `client_secret` could be updated programmatically.

### Describe Alternatives
Currently, secrets [must be rotated manually](https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/get-started/activate-azure-integrations/#update-app).

### Additional context
https://github.com/pulumi/pulumi-newrelic/issues/451

**Comment by pranav-new-relic** [comment]
Hi @guineveresaenger, thank you for reporting this issue. 

I think this wasn't implemented because the NerdGraph API (which is a dependency the New Relic Terraform Provider uses to create resources) doesn't have a mutation to update Azure credentials (like it does for create/delete) of the Azure account to be linked to New Relic, which may have been for security concerns with credentials; similar to what you've mentioned in the referenced issue. This is probably why the resource supports only a change to the name of the linked account in the update operation.

However, I can check with the team and revert soon, if this is feasible to be implemented. Thanks for notifying us.

**Comment by pranav-new-relic** [comment]
Update: We've added this to our backlog, and will pick it up for development based on our current priority of tasks. However, the update method would function in such a way that an update to the **client_secret** in the Terraform configuration would force the existing resource (linked account) to be destroyed and re-created with the new client_secret.

This is so, because we follow the same implementation with resources dealing with cloud integrations in the provider, owing to an absence of "update" mutations in NerdGraph to update linked cloud accounts/cloud integrations, probably due to security concerns.

**Comment by pranav-new-relic** [comment]
Hi, we've released a fix to this issue with [v3.27.2](https://github.com/newrelic/terraform-provider-newrelic/blob/v3.27.2/CHANGELOG.md) of the Terraform Provider.

As described in my previous comment, 
> owing to an absence of "update" mutations in NerdGraph to update linked cloud accounts/cloud integrations,

since cloud integrations on NerdGraph do not comprise endpoints to update an integration (or) a linked account, the `newrelic_cloud_azure_link_account` resource has been modified in such a way that if any of the arguments of the resource (except `name`) are changed or updated, with the next `terraform apply`, a **replacement** of the resource would be triggered, i.e. the resource would be destroyed and re-created with the updated attributes.

This can be identified in the output of `terraform plan` run after any of these arguments (not `name`) are updated - the output would indicate in **bold** that a subsequent `terraform apply` would force replacement of the resource in whcih arguments have been updated.

It is important to note that if only the `name` of this resource is updated, a replacement will not be triggered - however, if any other argument is updated, replacement would be triggered.

Closing this issue - thanks for reporting!
