### ISSUE TITLE
newrelic_alert_condition argument violation_close_timer rendering changes every time 

### ISSUE THREAD

**Issue by pneigel-ca** [newrelic/terraform-provider-newrelic#2398]
- [X] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [X] A list of [affected resources](#affected-resources) and/or data sources
- [X] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [X] Description of the [current behavior](#actual-behavior) (the bug)
- [X] Description of the [expected behavior](#expected-behavior)

### Terraform Version
Terraform v1.1.7

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_alert_condition`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
provider "newrelic" {
  region     = "US"
  api_key    = var.nr_api_key
  account_id = var.nr_account_id
}

resource "newrelic_alert_condition" "condition" {
  policy_id       = var.policy_id
  name            = var.alert_condition_name
  type            = var.alert_type
  entities        = var.entities
  metric          = var.metric
  runbook_url     = var.runbook_url
  condition_scope = var.condition_scope
  gc_metric       = var.gc_metric
  
  dynamic "term" {
    for_each = var.alert_content
    content {
      duration      = term.value["duration"]
      operator      = term.value["operator"]
      priority      = term.value["priority"]
      threshold     = term.value["threshold"]
      time_function = term.value["time_function"]
    }
  }
}
```

### Actual Behavior
When omitting optional argument `violation_close_timer`, the value in created resources is `72`. This means every time terraform plan/apply runs, it reverts this to a null value:

![image](https://github.com/newrelic/terraform-provider-newrelic/assets/48532268/cc55851a-c380-46a6-a604-7038dadf4092)

If you attempt to provide value `72` to match the current resource state, there is an exception that `72` is not a valid value which matches the documentation:

`Error: expected violation_close_timer to be one of [1 2 4 8 12 24], got 72`

### Expected Behavior
The value should be set to null in the remote resources or you should be able to provide the same value of `72` to prevent persistent differences in plan/apply.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan` or `terraform apply` when managing a `newrelic_alert_condition` with no value set for `violation_close_timer`, after it is created

**Comment by pranav-new-relic** [comment]
Hi @pneigel-ca - thank you for reporting this issue. I've tried reproducing this on my device, but unfortunately, haven't been able to (with the configuration you've specified). However, we did see a few issues similar to this in the past, and the probable cause of this could be that an unexpected API change is defaulting a null `violation_close_timer` to 72. Would you be able to share the debug logs you find when you apply `terraform apply` (by running the command `export TF_LOG=TRACE` followed by `terraform apply`) so we can understand this issue better? Thanks!

**Comment by pneigel-ca** [comment]
@pranav-new-relic thanks for responding to this issue so quickly!

[tf_trace.txt](https://github.com/newrelic/terraform-provider-newrelic/files/11801200/tf_trace.txt)

Attached is my trace output. Here is the full configuration without placeholders used for the plan, for your convenience.

```tf
resource "newrelic_alert_condition" "condition" {
  policy_id       = 2406896
  name            = "Heap Memory Usage"
  type            = "apm_jvm_metric"
  entities        = [1020524950]
  metric          = "heap_memory_usage"
  runbook_url     = "https://foo"
  condition_scope = "application"
  
  term {
      duration      = 5
      operator      = "above"
      priority      = "critical"
      threshold     = 40
      time_function = "all"
  }
  term {
      duration      = 5
      operator      = "above"
      priority      = "warning"
      threshold     = 30
      time_function = "all"
  }
}

terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
    }
  }
}

provider "newrelic" {
  region     = "US"
  api_key    = var.nr_api_key
  account_id = var.nr_account_id
}

variable "nr_api_key" {}

variable "nr_account_id" {}
```

Here is my current versions of tf/provider:
```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v3.24.2
```

And to summarize, here is the plan output after the resource has been created:

```tf
  # newrelic_alert_condition.condition will be updated in-place
  ~ resource "newrelic_alert_condition" "condition" {
        id                    = "2406896:33318619"
        name                  = "Heap Memory Usage"
      - violation_close_timer = 72 -> null
        # (8 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by pranav-new-relic** [comment]
@pneigel-ca it looks like this has something to do with how the underlying API processes alert conditions of type `apm_jvm_metric`. Sifting through the logs you've attached, it looks like `violation_close_timer` is added as 72 only with conditions of type `apm_jvm_metric` and not `apm_app_metric`, which is why I was unable to reproduce initially (as I tried creating an alert condition of the `apm_app_metric` type). I've opened a conversation with the API team to see if they know this better - will post here when I get an update from them.

**Comment by pranav-new-relic** [comment]
Hi @pneigel-ca - I'm back with a few updates 😄 

1. From the description of [this attribute](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/alerts-conditions-api-field-names/#violation_close_timer) in the New Relic docs, it appears that in the API request that is sent when an alert condition is created (from Terraform in our case), `violation_close_timer` is a mandatory argument to be specified when the alert condition is of type `apm_jvm_metric`. There is currently no validation in place in the Terraform resource to enforce this, because `violation_close_timer` is an attribute common to any alert condition type, but is mandatory only with a select few, in which case the API is defaulting this value to 72, leading to the drift we see when `terraform plan` is run after the first `apply`.

2. As you may see in the docs linked above, the list of valid values for this attribute does not comprise 72, but the API still defaults the attribute's value to 72 if it receives the value as null in the API request. This is unexpected, and the API team is looking into why this is so, and the associated update to the docs too. Once we get a heads up from them, we can proceed with adding 72 to the list of acceptable values (and preferably make it default) to prevent the error you've reported, which we've been discussing all about.

#### How do you work around this?
Since it appears that you're trying to add this attribute only to eliminate the drift shown (and not that you need this attribute), given that this is a mandatory attribute for the specified alert condition type, you can specify one of the accepted values (the list is in the screenshot of the error you've attached above, and also in the docs link I've attached). For instance, add this attribute with value `24`, and you won't see the drift anymore, since the API request would receive a non-null value and stop defaulting it to 72. I've tried this, and it works.

Hopefully, this should work in your case - while we take the fixes up in the background sometime, based on task priority in conjunction with the API team, to get this fixed.

**Comment by pranav-new-relic** [comment]
@pneigel-ca when you find time, let me know if the workaround listed in the description above helps fix the issue.

**Comment by pneigel-ca** [comment]
> @pneigel-ca when you find time, let me know if the workaround listed in the description above helps fix the issue.

Thanks for the update! I was able to confirm that providing an argument for this condition is working without issue and not showing drift 😄

**Comment by Tuzosdaniel12** [comment]
I have similar issue where is sending default of `violation_close_timer = 72` when I using `condition_scope = "application"`

My code looks like the following
```
# Appdex
resource "newrelic_alert_condition" "apdex" {
  policy_id       = newrelic_alert_policy.apm_alert_policy.id
  name            = "${var.full_name_env}-apdex"
  type            = "apm_app_metric"
  entities        = [data.newrelic_entity.apm.application_id]
  metric          = "apdex"
  condition_scope = "application"
  term {
    duration      = 5
    operator      = "below"
    priority      = "warning"
    threshold     = "0.6"
    time_function = "all"
  }
  term {
    duration      = 5
    operator      = "below"
    priority      = "critical"
    threshold     = "0.4"
    time_function = "all"
  }
}

```
Which results in the following error, this issue happen recently with different version of providers.Also had same code working for multiple projects.

```
Error: violation_close_timer only supported for apm_app_metric when condition_scope = 'instance'
```
Should I open a separate issue?

**Comment by pranav-new-relic** [comment]
Hi @Tuzosdaniel12 - the issue you're seeing is because of a slight bit of an issue we've run into with the latest version of the Provider, v3.25.1. This error message is not expected to be seen with a condition of type 'apm_app_metric' and scope 'application'. 

This issue has already been reported (https://github.com/newrelic/terraform-provider-newrelic/issues/2418) which we're working on, to correct this and send out a new release at the earliest. You can follow this issue. Meanwhile, to make your code work, please downgrade to v3.25.0 of the provider, and you can get it working, while we take a look into this further :)
