### ISSUE TITLE
`newrelic_nrql_alert_condition` - Error: You do not have the capability to use this feature: alerts.read.policy. & alerts.read.condition

### ISSUE THREAD

**Issue by vincentclee** [newrelic/terraform-provider-newrelic#2427]
We have a pretty large account and hitting what i believe to be API Rate Limiting issues. Our **NRDB query API requests per minute** limit usually hovers around the max limit of 3,000. New Relic support mentioned that this limit cannot be increased.

## Error
```
 ╷
 │ Error: You do not have the capability to use this feature: alerts.read.policy.
 │ 
 │   with module.███████████████████.newrelic_nrql_alert_condition.error_percentage_high["█████████"],
 │   on .terraform/modules/███████████████████/main.tf line 61, in resource "newrelic_nrql_alert_condition" "error_percentage_high":
 │   61: resource "newrelic_nrql_alert_condition" "error_percentage_high" {
 │ 
 ╵
 ╷
 │ Error: You do not have the capability to use this feature: alerts.read.condition.
 │ 
 │   with module.███████████████████.newrelic_nrql_alert_condition.heap_memory_usage_high_java["█████████"],
 │   on .terraform/modules/███████████████████/main.tf line 96, in resource "newrelic_nrql_alert_condition" "heap_memory_usage_high_java":
 │   96: resource "newrelic_nrql_alert_condition" "heap_memory_usage_high_java" {
 │ 
 ╵
```

Tweaking terraform's parallelism settings mitigates this for the most part, but this issue comes up once in a while.

```groovy
TF_CLI_ARGS_plan = "-parallelism=5"
TF_CLI_ARGS_apply = "-parallelism=5"
```

## New Relic Support replied: 

> Hi again,
> 
> As it turn out, the NRDB query API requests per minute rate limit has a hard limit of 3,000 queries per account per minute and cannot be increased.
> 
> More information can be found in our article: [NRQL query limits](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries/#query-count-limits)
> 

### Terraform Version
1.4.6

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_nrql_alert_condition`

### Terraform Configuration
```hcl
 Initializing provider plugins...
 - Finding newrelic/newrelic versions matching "~> 3.0, >= 3.7.0"...
 - Installing newrelic/newrelic v3.25.2...
 - Installed newrelic/newrelic v3.25.2 (signed by a HashiCorp partner, key ID EAFC5253DEFEAD23)
```
```hcl
provider "newrelic" {
  account_id = var.newrelic_account_id
  api_key    = "<newrelic-api-key>"
  region     = "US"
}

terraform {
  required_version = ">= 1.0"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.0"
    }
  }
}
```

### Actual Behavior
Intermittently, terraform will exit due to the errors `You do not have the capability to use this feature: alerts.read.condition.` or `You do not have the capability to use this feature: alerts.read.policy.`

### Expected Behavior
Terraform to retry when encountering API Rate Limiting 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by pranav-new-relic** [comment]
Hi @vincentclee - thank you for reporting this. We are currently aware of this issue, given there have been few others who have reported the same, an intermittent failure of `terraform apply` with the exact same errors you've mentioned under "Actual Behaviour". 

However, this is happening probably not due an API Rate limiting issue, but because of the migration of a few backing API services (such as authorization), which is occasionally leading to this error. The associated teams with the API are working on mitigating this; however, this is a bit time consuming as the teams are having a hard time to figure out the exact location this error is stemming out of. We shall keep you posted once we find the issue has started to disappear - and appreciate your patience :) thanks!

**Comment by pranav-new-relic** [comment]
@vincentclee we need a little help. Would you mind attaching debug logs of terraform apply (by setting TF_LOG=TRACE) when you see this occurrence? This would help teams currently looking into this understand things better. 

You can also mail it to pnandula@newrelic.com if you'd want to mail them instead of attaching them here. Thanks!

**Comment by vincentclee** [comment]
@pranav-new-relic question, does it matter if the error occurs on `terraform plan` vs `terraform apply`? I can create a test project and get the logs with `TF_LOG=TRACE` sent over.

**Comment by jodem** [comment]
Hello we have the same problem and I wanted to highlight it's an important one since this can prevent your customer (us) to upgrade their infrastructure in production because of Newrelic api problems. As you know there is not way to perform terraform updates and exclude a specific part (you can have a target but not an ignore param).

**Comment by pranav-new-relic** [comment]
Hi @jodem - we completely understand the importance of this, and teams associated with the alerts/authorization services are working hard to find a solution to this. It appears that a cloud migration of their backend services is causing these intermittent errors, and they're on it to find a way of doing it that would help reduce the errors we see by consuming services, such as Terraform.

The issue was taken note of, much prior to the creation of this GitHub issue (via other channels, as we received similar concerns via New Relic support cases), but as mentioned above - the teams are finding it hard to point to an exact cause, and is hence, a bit time consuming. We shall keep you posted when things look better - thanks!

**Comment by sxVova** [comment]
@pranav-new-relic hi, any updates regarding the issue?

**Comment by pranav-new-relic** [comment]
Hi, the backing API teams are having a hard time figuring out a solution, as this seems be happening intermittently when data migrations are performed (as mentioned in my previous comment) - however, given that this is affecting a lot of users, this has been prioritised and is being closely looked into. We don't have an update as of now, but shall keep you posted once there is one. Thanks!

**Comment by pranav-new-relic** [comment]
Hi all, we've heard from the engineering teams working on the API that the "capability" / "unknown" errors have cooled down a bit since the last couple of days (though not certain). Can someone please let me know if you're still seeing the issue? Thanks!

**Comment by pranav-new-relic** [comment]
Closing this issue, as it appears (from the updates we've received to, alongside the activity of this GitHub issue) that the issue has cooled down. Thank you for reporting this.
