### ISSUE TITLE
data "newrelic_synthetics_private_location" should return key

### ISSUE THREAD

**Issue by Francommit** [newrelic/terraform-provider-newrelic#2444]
### Feature Description
The code in https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/data_source_newrelic_synthetics_private_location.go doesn't return the key at all.

This key is needed when using that value to automate setting up private-minions / synthetic-job-managers

### Describe Alternatives
Hardcoding the key into my pipelines that setup private-minions / synthetic-job-managers allows you to use key, but the data source does not

### Additional context
I find it odd that the resource "newrelic_synthetics_private_location"

**Comment by pranav-new-relic** [comment]
Hi @Francommit - upon having a word with the Synthetics engineering team, we learn that the key of a private location is intended to be a confidential attribute, and values of such attributes are not usually not returned by resources/data sources in the Terraform Provider for security reasons - hence, unfortunately, we would not be able to take this forward. Thank you for reporting this.

**Comment by Francommit** [comment]
If that's the case. Why can the resource export the key value then?

**Comment by pranav-new-relic** [comment]
Hi @Francommit - I apologise for the confusion caused. Thank you for the catch - I've had a word with my team and we can go ahead with adding the key to the data source, as an attribute to be exported (a bit of misrepresentation from my side led to the confusion in the previous update - kindly ignore the same).

However, there exists a slight bit of a technical limitation to get this implemented at the earliest. When entities (of any type, which in this case is a private location) are queried, the NerdGraph API does not directly have an attribute **key** corresponding to an entity that is a private location (based on its type), and instead, the field **tags** comprises attributes specific to the type of the entity. Hence, this would be a slightly tedious change, as it would need few API schema changes in **newrelic-client-go** and the changes in the Terraform Provider to adapt to these changes and get the **key** from the tags. As the team is currently a bit occupied with priority tasks - we can take this up soon in the upcoming sprints, and will keep you posted once done.

In the interim, if you would like to unblock yourself, a possible workaround would be to fetch the key of the private location from GraphQL from inside Terraform (as a temporary solution, until we are done with the aforementioned changes), so that it can be used elsewhere to be specified in Terraform configurations. Feel free to take a look at the following example I've compiled, which helps fetch the **key** of a private location queried using the **newrelic_synthetics_private_location** data source.

`query.gql`
```gql
query ($guid: EntityGuid!) {
  actor {
    entity(guid: $guid) {
      accountId
      guid
      name
      tags {
        key
        values
      }
    }
  }
}
```
`variables.tf`
```hcl
variable "graphiql_url" {
  type = string
  default = "https://api.newrelic.com/graphql"
}

variable "api_key" {
  type = string
  default = "Your-New-Relic-API-Key"
}
```

`main.tf`
```hcl
terraform {
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
    }
    graphql = {
      source = "sullivtr/graphql"
    }
  }
}

provider "newrelic" {
  region = "US" # US or EU
}

locals {
  response = jsondecode(data.graphql_query.sample_query.query_response)
  info = local.response["data"]["actor"]["entity"]["tags"]
  key = [
    for tag in local.info : tag["values"][0]
          if tag["key"] == "key"
  ]
}

provider "graphql" {
  url = var.graphiql_url
  headers = {
    "Content-Type" = "application/json"
    "API-Key" = var.api_key
  }
}

// the data source
data "newrelic_synthetics_private_location" "foo" {
  name = "NP_TEST_PRIVATE_LOCATION"
}

// query sent to NerdGraph
data "graphql_query" "sample_query" {
  query_variables = {
    "guid" = data.newrelic_synthetics_private_location.foo.id
  }
  query  = file("query.gql")
  depends_on = [data.newrelic_synthetics_private_location.foo]
}

// the key may be used using the attribute local.key
output "x" {
  value = local.key
}
```

**Comment by pranav-new-relic** [comment]
Hi, an addition to the data source has been made (with the latest release, v3.27.0) to facilitate the export of the key of a private location. You can now export the key using a configuration similar to that of the following.

```hcl
data "newrelic_synthetics_private_location" "foo" {
  account_id = XXXXXX
  name = "Test Private Location"
}

output "private_location_key" {
  value = data.newrelic_synthetics_private_location.foo.key[0]
}
```

Closing this issue - thanks for reporting this.
