### ISSUE TITLE
GPG Key Expired

### ISSUE THREAD

**Issue by DemonICOLI** [newrelic/terraform-provider-newrelic#2481]
Hi there,

I'm unable to install the terraform providers as it seems the gpg key is expired:

`
Error: Failed to install provider
Error while installing newrelic/newrelic v3.17.0: error checking signature:
openpgp: key expired
`

**Comment by DemonICOLI** [comment]
Seems to be only present on old versions of the provider

**Comment by marshall-kiruba-selwyn** [comment]
Even we are facing this issue.

**Comment by DemonICOLI** [comment]
I can confirm it is present on 3.17 & 3.18

**Comment by rthorn-nr** [comment]
Hi @DemonICOLI , can I confirm with you whether you're using TF version 1.6.0?

Similar issues are starting to pop up since the new TF version was released yesterday:

https://github.com/hashicorp/terraform/issues/33984
https://github.com/vmware/terraform-provider-vra/issues/506
https://github.com/vmware/terraform-provider-wavefront/issues/126

For the time being, I was able to get around this issue two ways: if you want to stay on 3.17, you can downgrade to TF 1.5.7. Alternatively, you can upgrade your provider version. Thanks @marshall-kiruba-selwyn for confirming that this is working starting in 3.21

**Comment by DemonICOLI** [comment]
Hey @rthorn-nr ,

I can confirm the version we are using is 1.6.0, as is the one installed by default by `hashicorp/setup-terraform@v2` as of today

**Comment by pranav-new-relic** [comment]
Hey everyone, looks like [Terraform v1.6.1](https://github.com/hashicorp/terraform/releases/tag/v1.6.1) is out, which includes a fix to this bug.

> cli: Reverted back to previous behavior of ignoring signing key expiration for provider installation, since it's the provider registry's responsibility to verify key validity at publication time. [https://github.com/hashicorp/terraform/pull/34004]

I've tried `terraform init -upgrade` ing to multiple versions of the New Relic Terraform Provider <3.20.0 and this works with no error.

Can you all please try too, and confirm if things are now fine with Terraform v1.6.1? Thanks!

**Comment by rthorn-nr** [comment]
Thanks @pranav-new-relic , I confirmed that I'm able to use v1.6.1 to install v3.17 🎉 

@DemonICOLI are you unblocked with v1.6.1?

**Comment by DemonICOLI** [comment]
I can confirm that 1.6.1 does indeed works.

Thanks

**Comment by yuklia** [comment]
terragrunt version v0.38.12

terraform -v
Terraform v1.6.0
on darwin_amd64
is 1.6.1. l


newrelic", "3.17"

still an issue though 🤔
