### ISSUE TITLE
newrelic_log_parsing_rule issue with NRQL/query field

### ISSUE THREAD

**Issue by rsantos911** [newrelic/terraform-provider-newrelic#2484]
Hi there, 
We noticed an issue when create a 'newrelic_log_parsing_rule'

Terraform v1.1.7
NewRelic v3.27.2

How to reproduce: 
```sh
resource "newrelic_log_parsing_rule" "foo"{
    name        = "tf-bringFieldsFromJiraIntegration"
    attribute   = "message"
    enabled     = true
    grok        = "'DeploymentId': '%%{DATA:DeploymentId}', 'Application': '%%{DATA:Application}', 'DeploymentGroup': '%%{DATA:DeploymentGroup}',"
    lucene      = "logtype:linux_messages"
    nrql        = "SELECT message FROM Log WHERE aws.logGroup LIKE '%JiraIntegration%'"
}
```

Output : 
```sh
terraform plan && terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # newrelic_log_parsing_rule.foo will be created
  + resource "newrelic_log_parsing_rule" "foo" {
      + account_id = (known after apply)
      + attribute  = "message"
      + deleted    = (known after apply)
      + enabled    = true
      + grok       = "'DeploymentId': '%{DATA:DeploymentId}', 'Application': '%{DATA:Application}', 'DeploymentGroup': '%{DATA:DeploymentGroup}',"
      + id         = (known after apply)
      + lucene     = "logtype:linux_messages"
      + matched    = (known after apply)
      + name       = "tf-bringFieldsFromJiraIntegration"
      + nrql       = "SELECT message FROM Log WHERE aws.logGroup LIKE '%JiraIntegration%'"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

──────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee
to take exactly these actions if you run "terraform apply" now.

Terraform used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # newrelic_log_parsing_rule.foo will be created
  + resource "newrelic_log_parsing_rule" "foo" {
      + account_id = (known after apply)
      + attribute  = "message"
      + deleted    = (known after apply)
      + enabled    = true
      + grok       = "'DeploymentId': '%{DATA:DeploymentId}', 'Application': '%{DATA:Application}', 'DeploymentGroup': '%{DATA:DeploymentGroup}',"
      + id         = (known after apply)
      + lucene     = "logtype:linux_messages"
      + matched    = (known after apply)
      + name       = "tf-bringFieldsFromJiraIntegration"
      + nrql       = "SELECT message FROM Log WHERE aws.logGroup LIKE '%JiraIntegration%'"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
newrelic_log_parsing_rule.foo: Creating...
newrelic_log_parsing_rule.foo: Creation complete after 1s [id=23041]
╷
│ Warning: The grok pattern is not tested against log lines from the New Relic
│ 
│   with newrelic_log_parsing_rule.foo,
│   on main.tf line 7, in resource "newrelic_log_parsing_rule" "foo":
│    7: resource "newrelic_log_parsing_rule" "foo"{
│ 
╵

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
Console image:

![image](https://github.com/newrelic/terraform-provider-newrelic/assets/117755853/42b43214-b738-47a0-acaa-3a7f1d447e9a)

### expected behavior
Create the parse rule with Query field.

**Comment by pranav-new-relic** [comment]
Hi @rsantos911, I was able to reproduce the issue with your configuration. This seems to be an issue out of the provider; it is either with the UI or with the NerdGraph API.

When I try creating a log parsing rule with the following Terraform Configuration (the example listed in the docs of the Terraform Provider but with a different name)

```hcl
resource "newrelic_log_parsing_rule" "foo"{
  name        = "2484 Debug Log Parsing Rule"
  attribute   = "message"
  enabled     = true
  grok        = "sampleattribute='%%{NUMBER:test:int}'"
  lucene      = "logtype:linux_messages"
  nrql        = "SELECT * FROM Log WHERE logtype = 'linux_messages'"
}
```

it is applied successfully and I see the following in the UI.

<img width="906" alt="image" src="https://github.com/newrelic/terraform-provider-newrelic/assets/127438038/2870d740-7c44-4582-856a-c3ae444d0e7c">

However, when I use your configuration
```hcl
resource "newrelic_log_parsing_rule" "foo"{
  name        = "2484 Debug Log Parsing Rule"
  attribute   = "message"
  enabled     = true
  grok        = "'DeploymentId': '%%{DATA:DeploymentId}', 'Application': '%%{DATA:Application}', 'DeploymentGroup': '%%{DATA:DeploymentGroup}',"
  lucene      = "logtype:linux_messages"
  nrql        = "SELECT message FROM Log WHERE aws.logGroup LIKE '%JiraIntegration%'"
}
```

it is applied successfully and I see the following in the UI; it doesn't have the query.

<img width="860" alt="image" src="https://github.com/newrelic/terraform-provider-newrelic/assets/127438038/311add73-894e-4010-95a8-01d8cd24a77b">


Though in both cases, when I intercept the API request sent and response received, I find that the NRQL query is sent and the structure of both the requests is the same. This seems like the NRQL query might be invalid, which is why this could be happening, but I'm not sure - this is just a thought.

Response from NerdGraph when `terraform apply` is performed with the first configuration above
```gql
{
	"data": {
		"logConfigurationsCreateParsingRule": {
			"errors": null,
			"rule": {
				"accountId": 0,
				"attribute": "message",
				"createdBy": null,
				"deleted": false,
				"description": "2484 Debug Log Parsing Rule",
				"enabled": true,
				"grok": "sampleattribute='%{NUMBER:test:int}'",
				"id": "23050",
				"lucene": "logtype:linux_messages",
				"nrql": "SELECT * FROM Log WHERE logtype = 'linux_messages'",
				"updatedAt": "2023-10-11T18:01:28.874Z[UTC]",
				"updatedBy": null
			}
		}
	}
}
```

Response from NerdGraph when `terraform apply` is performed with the second configuration above (yours)
```gql
{
	"data": {
		"logConfigurationsCreateParsingRule": {
			"errors": null,
			"rule": {
				"accountId": 0,
				"attribute": "message",
				"createdBy": null,
				"deleted": false,
				"description": "2484 Debug Log Parsing Rule",
				"enabled": true,
				"grok": "'DeploymentId': '%{DATA:DeploymentId}', 'Application': '%{DATA:Application}', 'DeploymentGroup': '%{DATA:DeploymentGroup}',",
				"id": "23051",
				"lucene": "logtype:linux_messages",
				"nrql": "SELECT message FROM Log WHERE aws.logGroup LIKE '%JiraIntegration%'",
				"updatedAt": "2023-10-11T18:06:05.546Z[UTC]",
				"updatedBy": null
			}
		}
	}
}
```

This requires further investigation with the concerned team - I shall take a further look at this tomorrow to understand this better, and get in touch with the concerned team in the next few days to investigate into this occurrence. I shall post back an update when I hear back from the team. Thanks for reporting this issue.

**Comment by pranav-new-relic** [comment]
Hi @rsantos911, upon some experimentation, I found that if you modify your query to 
```
SELECT * FROM Log WHERE aws.logGroup LIKE '%JiraIntegration%'
```

(`*` replaces `message`), this is seen to work (the query of the log parsing rule is shown in the UI, in this case).

<img width="1668" alt="image" src="https://github.com/newrelic/terraform-provider-newrelic/assets/127438038/38e8d6ab-b811-4ace-ae4b-fd1305d8b811">

This is because apparently, the right syntax of NRQL queries that go with log parsing rules should be a `SELECT * FROM Log WHERE ....`, and the remainder of the query starting from `WHERE` is picked up by the UI (i.e., `SELECT * FROM Log` is expected to remain constant in queries of all log parsing rules). 

Though a better experience in this case would be that when you `terraform apply` a configuration comprising your original query, one would want to see an error stating that the NRQL query used does not fit well into this usecase. I have opened a conversation with the team that works with logs at New Relic - they shall evaluate the feasibility of this to see if an error can be thrown from NerdGraph in such a case.

Please let me know if the above query works for you. Thanks!

**Comment by rsantos911** [comment]
Hi @pranav-new-relic,
Thank you for your response.

Indeed, if I change to * that query works properly. 

Have a great week. Cheers!
