### ISSUE TITLE
Adding custom tags to Alert policies via Terraform script should be enabled

### ISSUE THREAD

**Issue by glingaraj** [newrelic/terraform-provider-newrelic#2492]
Hi Team,
We are trying to add custom tag to alert policy via terraform script but getting errors(_Attached_). But using NerdGraph API, we are able to add tags to alert policy successfully. Can you please do the needful so that using terraform we should be able to add custom tags to Alert policies as well?

**Note**: Adding custom tags to dashboard via terraform is successfully done.

**Actual Behavior**
Getting "invalid entity guid" or "Object has no argument error".
Please find attached for complete error details.

**Expected behavior**
Custom tags should be able to add to Alert policy via terraform script.

**Versions**
Terraform v1.5.3
NewRelic  v3.27.2

<img width="497" alt="Custom tag script" src="https://github.com/newrelic/terraform-provider-newrelic/assets/148505085/b74b3662-8bb6-47e9-b25d-689fa78bc328">

<img width="497" alt="Error" src="https://github.com/newrelic/terraform-provider-newrelic/assets/148505085/4cc917b2-ff06-4e14-86cd-a2437450ab32">

**Comment by pranav-new-relic** [comment]
Hi @glingaraj, can you please share the NerdGraph mutation you used to add tags to an alert policy?

It looks like the NerdGraph mutation which creates an alert policy **does not** have a `guid` in the attributes it exports. Since this mutation is used by the `newrelic_alert_policy` resource, as a result, the resource is also not capable of exporting a GUID. Since the entity tags resource expects the GUID of an entity to be supplied in the `guid` argument of the resource, you see the following errors:
- `Unsupported attribute` error, since you're trying to export a `guid` from the alert policy resource, though it is not an attribute that is exported by the resource
- `Could not validate account access to the following guids:` error, since the ID of the alert policy is being supplied to the `guid` argument of the `newrelic_entity_tags` resource

Ideally, it would not be possible to use the `newrelic_entity_tags` resource to add custom tags to an alert policy, as the current mutation on NerdGraph to create an alert policy doesn't seem to export the attribute `guid`. 

<img width="1676" alt="image" src="https://github.com/newrelic/terraform-provider-newrelic/assets/127438038/2cbbc8b4-5c3e-4178-b317-85a1126654d1">

<img width="305" alt="image" src="https://github.com/newrelic/terraform-provider-newrelic/assets/127438038/1e5eb4fb-df4a-482d-8f0f-704e9d24b5df">


This is why I would like to know how you were able to add tags to an alert policy via NerdGraph - was it by accessing the GUID of the alert policy elsewhere from the New Relic One UI? Thank you for the details, in advance :)

**Comment by pranav-new-relic** [comment]
Closing this issue as this doesn't seem to be immediately feasible, based on the findings I've posted above - we have, however, opened a conversation with the associated team to evaluate the feasibility of exporting the GUID of an alert policy via NerdGraph, and if this is feasible, we shall, subsequently, be able to modify code in the `newrelic_alert_policy_resource` to export the GUID of the policy and help add tags to it using `newrelic_entity_tags`. Thank you for reporting this issue.
