### ISSUE TITLE
Erro in module "newrelic-aws-cloud-integrations" v3.27.7

### ISSUE THREAD

**Issue by nandoin** [newrelic/terraform-provider-newrelic#2512]
Hi,

### Terraform Version
 1.6.4

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic-aws-cloud-integrations`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
    required_providers {
        newrelic = {
          source  = "newrelic/newrelic"
          version = "~> 3.27.7"
        }
}

provider "newrelic" {
  account_id = xxxxx
  api_key = "xxxx "   # Usually prefixed with 'NRAK'
  region = "US"                    # Valid regions are US and EU
}

module "newrelic-aws-cloud-integrations" {
    source = "github.com/newrelic/terraform-provider-newrelic/examples/modules/cloud-integrations/aws"
    
    newrelic_account_id     = xxxxxx
    newrelic_account_region = "US"
    name                    = "dev/qa"
    }

```

### Actual Behavior

│ Error: Unsupported block type
│ 
│   on .terraform/modules/newrelic-aws-cloud-integrations/examples/modules/cloud-integrations/aws/main.tf line 135, in resource "aws_kinesis_firehose_delivery_stream" "newrelic_firehose_stream":
│  135:     s3_configuration {
│ 
│ Blocks of type "s3_configuration" are not expected here.

### Expected Behavior
That works

### Steps to Reproduce

1. `terraform validate`

### Important Factoids
Running this terraform in Azure Devops Pipeline. Running local fail too.

**Comment by pranav-new-relic** [comment]
Hi @nandoin, TL;DR you're seeing this issue because you're on an older version of the Hashicorp AWS Terraform Provider (<v5).

I was able to reproduce the issue when I used v4.67.0 (which is the last release in v4) of the AWS Provider in `terraform init`, but not with any version succeeding v5 of the AWS Provider. 

This is because the AWS Terraform Provider had a change introduced with v5 in the resource `aws_kinesis_firehose_delivery_stream`, as a result of which the attribute `s3_configuration`, which was earlier an argument of this resource was made a **nested argument** - compare this example ([old version](https://registry.terraform.io/providers/hashicorp/aws/4.67.0/docs/resources/kinesis_firehose_delivery_stream#redshift-destination), [new version](https://registry.terraform.io/providers/hashicorp/aws/4.67.0/docs/resources/kinesis_firehose_delivery_stream#redshift-destination)) for a better idea. In light of this change, to keep our AWS integrations module up to date with the latest version of the AWS Provider, we had updated code in an older PR (#2380) to make `s3_configuration` a nested attribute, and since you're on an older version of the AWS Terraform Provider, there is a mismatch in configuration.

The solution would be to use v5 and above of the AWS Terraform Provider.

#### `terraform validate` results with v4.67.0 of the AWS Terraform Provider
```
user@~ Git-2512 % terraform init -upgrade

Initializing the backend...
Upgrading modules...
Downloading git::https://github.com/newrelic/terraform-provider-newrelic.git for newrelic-aws-cloud-integrations...
- newrelic-aws-cloud-integrations in .terraform/modules/newrelic-aws-cloud-integrations/examples/modules/cloud-integrations/aws

Initializing provider plugins...
- Finding hashicorp/aws versions matching "4.67.0"...
- Finding latest version of newrelic/newrelic...
- Finding latest version of hashicorp/random...
- Installing hashicorp/aws v4.67.0...
- Installed hashicorp/aws v4.67.0 (signed by HashiCorp)
- Using previously-installed newrelic/newrelic v3.27.7
- Using previously-installed hashicorp/random v3.5.1

Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform has been successfully initialized!
..
..

user@~ Git-2512 % terraform validate     
╷
│ Error: Unsupported block type
│ 
│   on .terraform/modules/newrelic-aws-cloud-integrations/examples/modules/cloud-integrations/aws/main.tf line 135, in resource "aws_kinesis_firehose_delivery_stream" "newrelic_firehose_stream":
│  135:     s3_configuration {
│ 
│ Blocks of type "s3_configuration" are not expected here.
╵
``` 

#### `terraform validate` results with v5+ of the AWS Terraform Provider

```
user@~ Git-2512 % terraform init -upgrade

Initializing the backend...
Upgrading modules...
Downloading git::https://github.com/newrelic/terraform-provider-newrelic.git for newrelic-aws-cloud-integrations...
- newrelic-aws-cloud-integrations in .terraform/modules/newrelic-aws-cloud-integrations/examples/modules/cloud-integrations/aws

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Finding latest version of newrelic/newrelic...
- Finding latest version of hashicorp/random...
- Using previously-installed newrelic/newrelic v3.27.7
- Using previously-installed hashicorp/random v3.5.1
- Installing hashicorp/aws v5.26.0...
- Installed hashicorp/aws v5.26.0 (signed by HashiCorp)

Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform has been successfully initialized!
..
..

user@~ Git-2512 % terraform validate
Success! The configuration is valid.
```
