### ISSUE TITLE
newrelic_synthetics_private_location data source returning masked keys

### ISSUE THREAD

**Issue by ttangsv** [newrelic/terraform-provider-newrelic#2521]
### Terraform Version
```
Terraform v1.6.0
on linux_amd64
```

### Affected Resource(s)
data source:
- `newrelic_synthetics_private_location`

### Terraform Configuration
```hcl
terraform {
  required_version = "~> v1.0"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "3.27.2"
    }
  }
}

variable "cloud_np_environment" {
  description = "Environments"
  type        = list(string)
  default     = ["dev", "st"]
}

resource "newrelic_synthetics_private_location" "location" {
  for_each = toset(var.cloud_np_environment)

  description = "The private location of the GCP ${each.key} environment"
  name        = "${each.key}-env"
}

data "newrelic_synthetics_private_location" "private_location" {
  count = length(var.cloud_np_environment)
  name  = "${var.cloud_np_environment[count.index]}-env"
}

resource "vault_generic_secret" "private_location" {
  count = length(var.cloud_np_environment)
  path  = "/newrelic/private_location"

  data_json = jsonencode({
    "key" = data.newrelic_synthetics_private_location.private_location[count.index].key[0]
  })
}
```

### Actual Behavior
Private location keys are masked even though they are created successfully in Vault

### Expected Behavior
Private location keys are created in Vault and they should NOT be masked.

### Steps to Reproduce
No issues with `terraform apply` as it can create the resource successfully. However `data.newrelic_synthetics_private_location.private.location[count.index].key[0]` is producing MASKED keys.

**Comment by pranav-new-relic** [comment]
Hi @ttangsv, thank you for reporting this issue. I've been working on identifying why the private location resource and data source have been returning masked keys since the recent past, while they were being returned them without any obfuscation earlier - and have discovered that it is an alteration of the backing NerdGraph API query that has led to this behaviour. 

Owing to a recent security consideration made by New Relic Synthetics, it was inferred that the NerdGraph API is expected to return the key of a private location in a masked format, and this change was made - as a result of which this behaviour is seen with the private location data source and resource in the Terraform Provider, which rely on the aforementioned NerdGraph query. Upon having a word with them, we obtain that this would continue to be the case, so we would probably not be able to return the key in an unmasked format, prior to how this functioned earlier.

**Comment by ttangsv** [comment]
Thank you @pranav-new-relic - I think this is an unnecessary security measure that makes automation difficult. We have automation that relies on retrieving private location keys via Terraform. The key is also stored in Hashicorp Vault through Terraform as you can see from my example Terraform configuration above. We also automated the configuration of synthetic job manager so it retrieves the key from Vault for that. During such process, the key is never exposed to human. This key is for **PRIVATE** locations which should be managed by New Relic customers so I don't understand why New Relic is taking such security measure to mask such important information from its customers. I may not see the big picture your Synthetics team sees in terms of security, but I hope they can see my use case and reconsider the decision.

**Comment by pranav-new-relic** [comment]
Hi @ttangsv - thanks for the feedback. We comprehend with what you've mentioned - however, owing to a broader context of security measures being implemented, this would continue to be the case with the key of the private location. We're looking into opening a conversation with them to understand the decision better so we can provide better context, however, this would take us time as we're juggling a couple of other issues at the moment. We shall keep you posted on this once we have an update. Thank you for understanding.

**Comment by pranav-new-relic** [comment]
Hi @ttangsv, this shall continue to be the case with keys returned by Private Locations, as I've mentioned in my previous comment. We learn from Synthetics that the key would continue to be treated a sensitive field, to prevent any unauthorized use that can be led to with the key. I shall be closing this issue. Thank you for understanding.
