### ISSUE TITLE
newrelic_monitor_downtime error

### ISSUE THREAD

**Issue by madgelackie** [newrelic/terraform-provider-newrelic#2545]
### Terraform Version
Terraform 1.1.4
New Relic Provider 3.28.1
Atlantis 3.19.0

### Affected Resource(s)
- `newrelic_monitor_downtime`

### Terraform Configuration

```
provider "newrelic" {
  account_id = <redacted>
  api_key = <redacted>
  region = <redacted>
}
```
Anonimised version of the resource we are trying to implement:
```
resource "newrelic_monitor_downtime" "test_downtime" {
  name          = "test:monitor-downtime"
  monitor_guids = [
    "redacted"  ]
  mode       = "ONE_TIME"
  start_time = "2024-01-10T13:00:00"
  end_time   = "2024-01-10T13:30:00"
  time_zone  = "UTC"
}
```

### Actual Behavior
The resource plans successfully but when we attempt to apply the plan we get the following error:
```
Error: strconv.Atoi: parsing "": invalid syntax

  with newrelic_monitor_downtime.sample_one_time_newrelic_monitor_downtime,
  on downtime.tf line 1, in resource "newrelic_monitor_downtime" "sample_one_time_newrelic_monitor_downtime":
   1: resource "newrelic_monitor_downtime" "sample_one_time_newrelic_monitor_downtime" {

time=2024-01-10T12:06:31Z level=error msg=1 error occurred:
	* exit status 1
```

This has been recreated in a different project trying to create the same resource type. 

### Expected Behavior
Running the apply command should have added the new resource to our New Relic account. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. add code for the new newrelic_monitor_downtime resource
2. `terraform plan`
1. `terraform apply`

### Important Factoids
We're running this using https://www.runatlantis.io/

**Comment by pranav-new-relic** [comment]
Hi @madgelackie, thank you for reporting this issue. I've tried reproducing this issue (also using your version of Terraform, 1.1.4), but haven't been able to reproduce this (I've tried in both regions, US and EU). 

Just to be sure - are you still able to reproduce this issue using the configuration you've attached? If not, would you be able to attach the configuration with which you were able to see the issue? It might also be helpful to attach the entire error message you're seeing.

Additionally, based on the error message you've attached I see - the `strconv.Atoi()` method is used only at very few points in the implementation of this resource, and the only point that seems relevant to this configuration (i.e., creation of a `ONE_TIME` monitor downtime) is where it tries to get an account ID from the environment, so it might be worth checking if `NEW_RELIC_ACCOUNT_ID` in your environment is configured right - this is just a guess, however.

P.S.
> This has been recreated in a different project trying to create the same resource type.

Just to be clear - by this, do you mean to say you were able to get it work, without an error, in a different project?

Thanks!

**Comment by madgelackie** [comment]
Hey, thanks for looking at this :) 
The `NEW_RELIC_ACCOUNT_ID` should be okay - it's passed in here the same way that it is for all of our other resources.  Am I right in thinking that in this resource implementation it is expecting the [account id to be a string](https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/resource_newrelic_monitor_downtime.go#L43C29-L43C29)?  It looks like in other resources the value is expected to be an `int`, and in our environment configuration the account id is an `int`.  The strconv.Atoi() method is trying to convert a string to an int so that would make sense that we are getting that error.  
(The same problem was encountered when we tried to recreate the issue in a different project - we got the same error, sorry if I wasn't clear on that).
Thanks

**Comment by pranav-new-relic** [comment]
Hi @madgelackie, thank you for clarifying. I'd like to explain a few things - 

> Am I right in thinking that in this resource implementation it is expecting the account id to be a string?

Yes and no; the account ID is defined as a string in the definition of the resource; however, in the Terraform configuration, the value of `account_id` can be specified both as "XXXXXXX" or XXXXXXX (as an integer or a string), and Terraform will interpret this as a string anyway, so specifying it as an integer or a string should not be the cause of the issue. Anyway, I do not see the attribute `account_id` in your configuration (`account_id` is optional in the configuration of monitor downtimes, just to help specify an `account_id that` is not `NEW_RELIC_ACCOUNT` ID in the environment), so this shouldn't be a problem.

> The strconv.Atoi() method is trying to convert a string to an int so that would make sense that we are getting that error.

Correct; but the error message you'd posted in your previous comment says `Error: strconv.Atoi: parsing "": invalid syntax`, which clearly indicates that one of the strconv.Atoi() functions in the code is trying to convert an empty string into an integer. With a `ONE_TIME` monitor downtime, the only point in the code that uses this function is the part that gets the `account_id`, which is why I'd asked if this has something to do with an empty `account_id`.

I was able to reproduce this issue today by setting `NEW_RELIC_ACCOUNT_ID` as an empty string in the environment `""`, and then trying to `terraform plan` and `terraform apply` the following configuration

```hcl
provider "newrelic" {
  region = "US"
  account_id = XXXXXXX
  api_key = "Redacted-API-Key"
}

resource "newrelic_monitor_downtime" "test_downtime" {
  name          = "test:monitor-downtime"
  mode          = "ONE_TIME"
  start_time    = "2024-01-10T13:00:00"
  end_time      = "2024-01-10T13:30:00"
  time_zone     = "UTC"
}
```

<img width="715" alt="image" src="https://github.com/newrelic/terraform-provider-newrelic/assets/127438038/c23f0169-c27f-4580-9ae4-d6457230133a">

This also happened when I completely removed `NEW_RELIC_ACCOUNT_ID` from my environment. Hence, I still think there might be a discrepancy with the `NEW_RELIC_ACCOUNT_ID` in your environment. To fix this, you might need to perform either of the following - 
- add the `account_id` you've added in the `provider{}` block to the resource `newrelic_monitor_downtime` too, simply as `account_id = XXXXXXX`
- make sure the environment variable `NEW_RELIC_ACCOUNT_ID` has a valid account ID and is non-null (and exists)

This is what you'll need to do to fix the issue, but I believe we need to make a few tweaks to the code to throw a better error and not this string parsing error, to let users know that `NEW_RELIC_ACCOUNT_ID` is missing in the environment, which we'll plan on doing based on current priorities.

Let me know if this helps. Thanks!

**Comment by madgelackie** [comment]
Great, adding the account_id into the resource has resolved the issue.  
Thanks for the explanation and pointers. 
In the resource documentation the entry for the account_id argument notes that the account_id in the provider{} is the next default value if there's nothing specified in the environment but is that maybe not happening?

**Comment by pranav-new-relic** [comment]
Looks like we ran into a bit of typo there - the sentence was rather supposed to be
> Defaults to the value of the environment variable `NEW_RELIC_ACCOUNT_ID` if not specified.

and not 
> Defaults to the value of the environment variable `NEW_RELIC_ACCOUNT_ID` (or the `account_id` specified in the provider{}), if not specified.

The ideal behaviour is to try and fetch an `account_id` from inside the configuration of the resource. If it doesn't exist, the next choice would be the `NEW_RELIC_ACCOUNT_ID` in the environment - we might need to see if defaulting this to the `account_id` is feasible in the absence of `NEW_RELIC_ACCOUNT_ID` in the environment.

Thanks for helping identify this - we'll get this updated soon :)

**Comment by madgelackie** [comment]
Fabulous.  Thanks for all your help.
