### ISSUE TITLE
Please add ignore time range to query dashboard variables

### ISSUE THREAD

**Issue by dmurphyfa** [newrelic/terraform-provider-newrelic#2609]
### Feature Description
In the UI it is possible to select ignore time range when creating a dashboard query variable, but it is not possible via the TF provider. This also defaults to true when created via TF which leads to an incomplete list of options vs what would be expected for the time range

### Describe Alternatives
Currently you must manually unselect this after every deploy of a dashboards to disable this behaviour

### Additional context

![Screenshot 2024-03-20 at 09 49 53](https://github.com/newrelic/terraform-provider-newrelic/assets/146190975/2f7aeb96-3e52-40d5-ac82-5152a1519049)

**Comment by pranav-new-relic** [comment]
Hi @dmurphyfa, changes for this have been made and have recently been merged (and are awaiting a release). We shall keep you posted when the change is out. Thank you for reaching out.

**Comment by pranav-new-relic** [comment]
@dmurphyfa this could be the fastest we've closed an issue/reached resolution - coincidentally because your ask was in alignment with the timelines of our development for this :) 

We've just released v3.33.0 of the Terraform Provider which [includes a new `options` field for variables](https://registry.terraform.io/providers/newrelic/newrelic/3.33.0/docs/resources/one_dashboard#nested-variable-blocks) that includes `ignore_time_range` which helps perform what we've discussed in this thread. Please check it out. Thanks for reporting!
