### ISSUE TITLE
Feature Request: Add the Ability to Add Users to Groups

### ISSUE THREAD

**Issue by RoseSecurity** [newrelic/terraform-provider-newrelic#2667]
### Feature Description

- Would it be possible to control adding `newrelic_user`'s to groups via their resource? This is currently available using the `newrelic_group`, but I believe this would be beneficial. The following is an example:

```hcl
resource "newrelic_user" "foo" {
  name      = "Test New User"
  email_id  = "test_user@test.com"
  user_type = "CORE_USER_TIER"
  group     = data.newrelic_group.foo.id
}
```

### Describe Alternatives

While it is currently possible to add users to groups via the `newrelic_group` resource, I believe it would be beneficial to have this option via the `newrelic_user` resource

**Comment by pranav-new-relic** [comment]
Thanks for creating this issue @RoseSecurity. While it is feasible on NerdGraph to be able to add support for adding groups to users in the `newrelic_user` resource, our team opines that it would be a better approach to have the functionality of adding users to groups confined to the `newrelic_group` user, just so we maintain better feature parity with the hierarchy of groups, and the options available to be configured against groups in the UI (for instance, now that users can be added to groups, and there shall be upcoming support in future to configure roles with groups, functionality to revoke/grant roles can also be added to the `newrelic_group` resource too (based on feasibility), which could probably help use `newrelic_group` as the starting point for user and access management).

That being said, this is certainly a valid request - we would like to close this for now in order to allow our team greater emphasis on other active/open issues, but shall reconsider this if we find this issue gaining greater traction in future. Thank you for reaching out!
