### ISSUE TITLE
Provide better validation and user feedback for invalid alert policy config

### ISSUE THREAD

**Issue by ctrombley** [newrelic/terraform-provider-newrelic#279]
Related to #278 .

When attempting to create an alert policy with multiple `critical` or `warning` terms, the user is presented with an unfriendly "Internal Server Error".  We should provide validation in the provider for this case that presents a more readable error for the user.

### Affected Resource(s)
- newrelic_alert_policy

### Terraform Configuration Files
```hcl
data "newrelic_application" "foo" {
  name = "foo"
}

resource "newrelic_alert_policy" "foo" {
  name = "foo"
}

resource "newrelic_alert_condition" "foo" {
  policy_id = newrelic_alert_policy.foo.id

  name        = "Apdex (low)"
  type        = "apm_app_metric"
  entities    = [data.newrelic_application.foo.id]
  metric      = "apdex"
  condition_scope = "application"

  term {
    duration      = 5
    operator      = "below"
    priority      = "critical"
    threshold     = "0.7"
    time_function = "all"
  }

  term {
    duration      = 10
    operator      = "below"
    priority      = "critical"
    threshold     = "0.85"
    time_function = "all"
  }
}
```

**Comment by emetcalf9** [comment]
This is not going to be fixed for non-NRQL conditions because these are being removed next year. More details in this announcement: https://discuss.newrelic.com/t/big-news-for-alerts-and-applied-intelligence/161436

I tested this same scenario with a NRQL condition, and confirmed that an error is raised during the `plan` stage telling the user that multiple "critical" blocks are not allowed.
