### ISSUE TITLE
API permission issues with 2.0.0 provider

### ISSUE THREAD

**Issue by timothy-spencer** [newrelic/terraform-provider-newrelic#691]
### Terraform Version
Terraform v0.12.24

### Affected Resource(s)
- newrelic_alert_policy
- newrelic_alert_channel

### Terraform Configuration Files
https://gist.github.com/timothy-spencer/51a1b1afe98d1d987fa1d36029b57fe3

I also have these set:
```
laptop$ env | grep NEW
NEW_RELIC_ACCOUNT_ID=<7 digit number>
NEW_RELIC_API_KEY=NRAA-XXX
NEW_RELIC_ADMIN_API_KEY=XXX
laptop$ 
```
The NRAA-XXX key is my personal key, and the XXX key is the main API key from the https://rpm.newrelic.com/accounts/<7 digit number>/integrations?page=api_keys page, but I have tried this with one key or another set, and with the values switched.

### Debug Output
https://gist.github.com/timothy-spencer/737065d939d0f8d0b89b322cdc514076

### Expected Behavior
The NewRelic provider should be able to create anything it needs with the keys it has.  I keep going back to  https://www.terraform.io/docs/providers/newrelic/guides/provider_configuration.html#configuration-via-environment-variables to try to see what I should do, but none of those API keys seem to be doing the trick, so either I'm doing it wrong, or there is a bug.

### Actual Behavior
The API returned 401 result codes and terraform bombed out.

### Steps to Reproduce
1. Set environment variables: 
```
export NEW_RELIC_ACCOUNT_ID=<7 digit number>
export NEW_RELIC_API_KEY=NRAA-XXX
export NEW_RELIC_ADMIN_API_KEY=XXX
```
2. `terraform apply`

### Important Factoids
This code is a module in a MUCH larger terraform deployment, so it's kinda hard to figure out what is useful and how to separate that out.  For now, I have grepped the provider plugin name, and I think I have a workable main.tf in the gist that should work.  Let me know if more is needed.

It is entirely possible that I haven't created the proper API keys or haven't configured them properly, or there's something else that I have missed!  If so, then perhaps the bug is in the documentation or me?  I feel like I've tried about everything but regenerating the main NewRelic API key (which would require a lot of work to update in other places).  Anyways, let me know what you think.  Thanks!

**Comment by robertjrussell99** [comment]
I get the same issue. From the debug output i think it's using the header "Api-Key" instead of "X-Api-Key" for the REST API.

**Comment by wellcast** [comment]
Same issue here, I've tried different combinations trying to get REST API plus nerdgraph to work. Rolling back to previous version atm.
Followed references are:
https://www.terraform.io/docs/providers/newrelic/index.html
https://docs.newrelic.com/docs/apis/get-started/intro-apis/types-new-relic-api-keys

**Comment by sanderblue** [comment]
Hi all, thanks for filing an issue and including some good details about your scenarios. For those that are updating to v2.0.0, there are a few subtle (but important) changes with the API keys which you might have already seen in the updated docs, but it sounds like we can improve them a bit maybe? 

Taking a look at @timothy-spencer's environment variables reveals the first subtle thing we need to adjust.
-  In v2.0 the env variable `NEW_RELIC_API_KEY` must be set to your _Personal API Key_ (not the Admin API Key or your user-scoped REST API Key). From the provided env variables above, it would appear it's either set to the Admin API key or it's set to your user-scoped REST API Key, which is likely causing the problem.
    - Navigate to the following page to find your **Personal API Key**
       **`https://account.newrelic.com/accounts/{accountID}/users/{yourUserID}`**
       Then click on the "API Keys" tab. If it's blank, you'll need to generate a new Personal API Key here, but if you've already done that you should see an API key that likely has an `NRAK` prefix. This is your Personal API Key. More information on the Personal API Key can be viewed [here](https://docs.newrelic.com/docs/apis/get-started/intro-apis/types-new-relic-api-keys#personal-api-key)

We also provided a [migration guide](https://www.terraform.io/docs/providers/newrelic/index.html#update-the-environment) to facilitate a smoother transition, which you might have already discovered and referenced and if that's the case, we'd like to know how we can improve it.

Regarding @robertjrussell99's mention of the different API key headers, this is expected - this is a temporary thing during the transition to only requiring the Personal API Key. The issue in this case seems to be an incorrect API key. It looks like it's likely the user's regular REST API Key based off Timothy's comments and since the prefix is `NRAA-` - i.e `headers="{\"Api-Key\":[\"NRAA-XXX\"] ...` should be `headers="{\"Api-Key\":[\"NRAK-XXX\"]`.

Apologies for the confusion around the multiple different types of API keys. These sorts of things will be a thing of the past as we transition to only needing the Personal API Key, but we're in a transition period. We are continuing to make updates to the documentation and welcome any additional feedback from the community to help makes things more clear and concise. 

Please let us know if this helps solve the issue as it will help inform us how we can improve our documentation and guides. And if this doesn't solve the issue, we're happy to continue to help out as best we can. Thanks!

**Comment by wellcast** [comment]
Hi @sanderblue 
Thanks for the additional information. 
Unfortunately, I had no luck with the v2 migration.

Terraform v0.12.26
Provider 2.1.1

How my provider definition looks like:

`provider "newrelic" {
  api_key = "NRAK-....."
  account_id = ....
  region     = "EU"
  version = "~> 2.1.1"
}`

The request made to `https://synthetics.eu.newrelic.com` has `X-Api-Key":["NRAA-..."]` as expected. 
It fails with `HTTP 401 Unauthorized`.

From resources converted from type data newrelic_application to newrelic_entity I get:
`403 Sorry – You've reached an error on New Relic
2020/06/24 14:25:24 [ERROR] <root>: eval: *terraform.EvalReadData, err: 403 response returned
2020/06/24 14:25:24 [ERROR] <root>: eval: *terraform.EvalSequence, err: 403 response returned
2020/06/24 14:25:24 [TRACE] [walkRefresh] Exiting eval tree: data.newrelic_entity.x`

Any direction what I could try or additional information to provide?
Thank you

**Comment by timothy-spencer** [comment]
Hey, I got sidetracked with some other problems, and just now managed to track this issue back down in the new location.  Sorry about that!

The hint about what API key was what helped me out.  I thought that the Admin API key was the Personal API key, since it was assigned to me.  Perhaps a good way to help prevent that confusion might be to document that the keys should start with NRAK- and NRAA-, and maybe put in the URLs where you can get them like you did for me above.

In any case, setting those keys properly seems to have done the trick, because I am now having NewRelic complain about my conditions having invalid values, which is totally a problem with my stuff.  :-)  Thanks!  I'm going to close the issue.
