### ISSUE TITLE
Not possible to set "violation_time_limit" to 0 (avoiding closing violation)

### ISSUE THREAD

**Issue by echoAlexey** [newrelic/terraform-provider-newrelic#767]
Hi,

expected **violation_time_limit** for **newrelic_nrql_alert_condition** is one of [ONE_HOUR TWO_HOURS FOUR_HOURS EIGHT_HOURS TWELVE_HOURS TWENTY_FOUR_HOURS]

seconds also do not support such case. 

expected **violation_time_limit_seconds** to be one of [3600 7200 14400 28800 43200 86400]

No way to disable auto-closing violations.

**Comment by echoAlexey** [comment]
Also it is worth to make this variable consistent with **newrelic_infra_alert_condition** which has **violation_close_timer** integer.

**Comment by sanderblue** [comment]
Hi @echoAlexey, thanks for submitting this ticket. As it currently stands, the underlying API does not support setting `violation_time_limit` to `0`. The attribute `violation_time_limit` maps to [`violationTimeLimit`](https://api.newrelic.com/graphiql?#query=mutation%20%7B%0A%20%20alertsNrqlConditionStaticCreate%28accountId%3A%202520528%2C%20condition%3A%20%7BviolationTimeLimit%3A%20EIGHT_HOURS%7D%29%0A%7D%0A) in the NerdGraph API. That being said, we'll take a look at the upstream API and see what we can do. Some new features are in the works for the API that might facilitate this request to some degree. 

Regarding the use of integers for `violation_close_timer` in `newrelic_infra_alert_condition`: Currently the `newrelic_infra_alert_condition` resource leverages the [Infrastructure Alerts API](https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/infrastructure-alert-conditions/rest-api-calls-new-relic-infrastructure-alerts) which has a slightly different resource data structure. Since the [NerdGraph API](https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph) is the future-facing API, our data types will be aligned with the GraphQL types for the `newrelic_nrql_alert_condition`. Check out the [NerdGraph API Explorer](https://api.newrelic.com/graphiql) for more details about the surface area of the API. As we move forward, we're in the process of standardizing on this API for all applicable resources. 

As a general note, the guidance from the Alerts team here at New Relic is to use NRQL alert conditions which are the future facing form of alert conditions.

**Comment by sanderblue** [comment]
Closing out this issue, but we'll open a feature request for this with the upstream API.
