### ISSUE TITLE
Support visualization type "inventory" in dashboard widgets

### ISSUE THREAD

**Issue by vinuthnag** [newrelic/terraform-provider-newrelic#837]
While importing the dashboard, the Visualization type of one of the widgets is "inventory".While trying to apply the imported dashboard, terraform unable to identify the widget of which visualization type is inventory.Getting an error message saying "inventory" is not a valid type. Can you please include support for "inventory" as well.
After going through the codebase of valid visualization types, I found "inventory" is not a part of valid visualization types.
https://github.com/newrelic/terraform-provider-newrelic/blob/master/newrelic/structures_newrelic_dashboard.go#L106

**Comment by zlesnr** [comment]
Good catch, thank you for raising the issue.  Are you interested in sending a PR for this change?

**Comment by sanderblue** [comment]
The widget type `inventory` doesn't seem to be on the list of [supported widget types](https://docs.newrelic.com/docs/insights/insights-api/manage-dashboards/insights-dashboard-api#supported) for the Dashboard REST API. 

However, the Dashboard REST API is currently being "upgraded" to our NerdGraph API and which will also involve some new features and capabilities.

Once the new Dashboards API is ready to go, this will be included if the new API supports it. 

Closing since we're capturing this work in a feature ticket for adding the new Dashboard capabilities here: #939
