### ISSUE TITLE
Getting timeout error when performing a terraform plan/apply against newrelic_synthetics_monitor resource

### ISSUE THREAD

**Issue by selvan1978** [newrelic/terraform-provider-newrelic#884]
**Terraform Version**

Terraform v0.13

**NewRelic Provider Version**

provider.newrelic v2.6.1

**Affected Resource(s)**

newrelic_synthetics_monitor

**Terraform Configuration Files**

resource “newrelic_synthetics_monitor” “testmonitor” {
name = “test”
type = “SIMPLE”
frequency = 5
status = “ENABLED”
locations = [“AWS_US_EAST_1”, “AWS_US_EAST_2”]
uri = “https://example.com/”
validation_string = “success”
}

**Issue**

I have setup newrelic synthetic monitoring using terraform (Command Line). I am getting below error intermittently.

![image](https://user-images.githubusercontent.com/53402695/93360981-eecab680-f861-11ea-876b-798910abb511.png)

I have tried to execute below command using my admin API key and working fine.

curl -v
-H ‘X-Api-Key:{Admin_User_Key}’ https://synthetics.newrelic.com/synthetics/api/v4/monitors

Thanks,
Selvan.

**Comment by sanderblue** [comment]
Hi @selvan1978, that's odd for sure. I wonder if playing with the [parallelism](https://www.terraform.io/docs/commands/apply.html#parallelism-n) number could help with this. It defaults to 10, but I would  probably try using something like `-parallelism=4` to see how things go and make adjustments if needed. 

Are you getting any specific error codes by any chance. Any extra helpful log output when use debug or trace level logs (sensitive data redacted)? Either way we'll pass along this information to the upstream API folks so they're aware as well. And if you're still seeing issues after trying some different parallelism values, we'll dig in a bit more.

**Comment by selvan1978** [comment]
Thanks @sanderblue. I have used -parallelism=2 and -parallelism=1 and working fine. As of now i have not noticed any time-out issue. I will keep monitor. Thanks for your help.

**Comment by chrisreed87** [comment]
Seeing the same behavior here as well, only with certain resources:
 - `newrelic_synthetics_alert_condition`
- `newrelic_alert_policy` (data)

but like `newrelic_synthetics_monitor` (rescource) works fine

```
Error: POST https://api.newrelic.com/v2/alerts_synthetics_conditions/policies/415579.json giving up after 4 attempt(s): Post "https://api.newrelic.com/v2/alerts_synthetics_conditions/policies/415579.json": dial tcp 0.0.0.0:443: connect: connection refused
```

**Comment by chrisreed87** [comment]
Never mind, i'm a dope, my DNS (Pi-Hole) was blocking `api.newrelic.com/*`

**Comment by zlesnr** [comment]
How goes the testing @selvan1978?

**Comment by rdhar** [comment]
Just ran into this as well, while managing a number of ping monitors in the triple digits along with several scripted browser ones.

For scaling, usually run with `-parallelism=50` so dropping down to `5` is a significant blow to response speed. Any idea why this happens to impact `newrelic_synthetics_monitor` disproportionately? Could it because they're [multi-purpose/over-loaded](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_monitor) with attributes of each of the different monitor types: `SIMPLE`, `BROWSER`, `SCRIPT_BROWSER`, and `SCRIPT_API`?

 Have yet to come across any similar rate-limiting issue with the thousands of NRQL alert conditions deployed across dozens of provisioned accounts.
