### ISSUE TITLE
New Relic Terraform Provider "newrelic_nrql_alert_condition" resource issue

### ISSUE THREAD

**Issue by sri-shetty** [newrelic/terraform-provider-newrelic#894]
### Terraform Version
0.13.3

### Affected Resource(s)
Please list the resources as a list, for example:
- newrelic_nrql_alert_condition

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "newrelic_nrql_alert_condition" "nrql_alert" {
    policy_id = newrelic_alert_policy.golden_signal_policy.id

    name    = "high_throughput"
    type    = "static"
    violation_time_limit = "one_hour" # optional but required
    value_function = "single_value" # optional but required
    
    # one of `since_value` or `evaluation_offset` must be configured for block `nrql`
    nrql {
        query   = "SELECT count(*) FROM Transaction WHERE appName ='WebPortal'"
        evaluation_offset = 3
    }
    
    critical {
        operator              = "above"
        threshold             = 400
        threshold_duration    = 300
        threshold_occurrences = "ALL"
    }
}
```

### Expected Behavior
Here is the link to documentation - https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/nrql_alert_condition.

The Terraform resource "newrelic_nrql_alert_condition", as per the documentation arguments:
1. violation_time_limit is optional, if violation_time_limit_seconds is specified but violation_time_limit_seconds is deprecated. Via New Relic Alert UI, I could create NRQL alert condition, without selecting a value for the "violation_time_limit" argument.
2. value_function is optional but I get error if not entered. Default value is not getting assigned. Via New Relic Alert UI,  I could create NRQL alert condition, without entering a value for the "value_function" attribute.
3. evaluation_offset is optional but I get error if not entered. Default value is not getting assigned. Via New Relic Alert UI, I could create NRQL alert condition through the UI, without entering a value for the "evaluation_offset" attribute.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by eager** [comment]
We’re experiencing this, too. We were especially surprised, because `plan` succeeds for this configuration, but `apply` fails.

**Comment by zbintliff** [comment]
THe error I'm getting is:
```
A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Expected a value of type \"ViolationTimeLimit\" but received: 2592000"}]
```

**Comment by sanderblue** [comment]
Hi @sri-shetty, what version of the Terraform provider are you using?

**Comment by sri-shetty** [comment]
> Hi @sri-shetty, what version of the Terraform provider are you using?

v2.7.1

**Comment by sanderblue** [comment]
Hi @sri-shetty, thanks for getting back to me with the version. To answer your questions at a high level, there are programmatic reasons for why things are optional and/or deprecated due to how the Terraform core SDK handles state. Due to the migration from the REST API to the future-facing NerdGraph API, handling backward compatibility had to be implemented in a certain way. We followed Terraforms [deprecation guidelines](https://www.terraform.io/docs/extend/best-practices/deprecations.html) to ensure backwards compatibility. 

> 1. violation_time_limit is optional, if violation_time_limit_seconds is specified but violation_time_limit_seconds is deprecated. Via New Relic Alert UI, I could create NRQL alert condition, without selecting a value for the "violation_time_limit" argument.

Unless I'm misreading, I think the documentation here is accurate in this case. `violation_time_limit` is technically optional because you can set `violation_time_limit` _or_ `violation_time_limit_seconds`. I would recommend setting `violation_time_limit` since it's future-facing. Unfortunately setting default values here would cause perpetual drift since the data types are completely different in NerdGraph API (strings) compared to the REST API (integers) in the case of `violation_time_limit`, thus is one or the other. 

<br><br>

> 2. value_function is optional but I get error if not entered. Default value is not getting assigned. Via New Relic Alert UI, I could create NRQL alert condition, without entering a value for the "value_function" attribute.

Thanks for mentioning this. It looks like this is a matter of having better clarity in our docs about when to use this attribute. Technically speaking, `value_function` is optional because it doesn't apply to all types of NRQL alert conditions - `value_function` only applies to **_static_** conditions. I will update the docs with this detail.

<br><br>

>  3. evaluation_offset is optional but I get error if not entered. Default value is not getting assigned. Via New Relic Alert UI, I could create NRQL alert condition through the UI, without entering a value for the "evaluation_offset" attribute.

Similar to the scenario above, you must provide `evaluation_offset` _or_ `since_value`. Again, due to how Terraform handles state, we can't set default values to the new `evaluation_offset` attribute because it would cause perpetual drift due to different data types - the old data type was a string and the new data type is an integer. Thus, you are required to set at least _one_ of those two attributes, preferably `evaluation_offset` because it's the new attribute.  

I'll see what I can do to help explain these caveats with a bit more clarity in our documenation.

**Comment by eager** [comment]
@sanderblue the explanation makes sense, but is there a way for `terraform plan` to catch the either-or requirement for these properties? We use `plan` in CI, so that we don't merge configurations that won't successfully `apply`.

**Comment by sanderblue** [comment]
We have validation around `violation_time_limit` and `violation_time_limit_seconds`, but we'll need to look into the others with regard to catching things during `terraform plan`.

**Comment by sanderblue** [comment]
Hi @gambrell, out of curiosity do you have a use case to keep a violation open indefinitely? Currently the API does not support this, but I will relay your use case and feedback to our alerts team to see what we can do there.

**Comment by zlesnr** [comment]
I believe the plan is to eventually remove the ability from the UI to leave a violation open indefinitely.  We're ahead of the curve because we're using the new API, so you should prepare for the day when that behavior is no longer available.

**Comment by gambrell** [comment]
@sanderblue We do not want alerts to close until the problem is resolved.  If it auto closes then we no longer know we have a problem.  Or will the alert close and the alert condition continue to be met so it opens again?

**Comment by zlesnr** [comment]
Hi @gambrell, I believe the violation won't trigger again until the condition has returned to normal.  This project is implementing the API as designed by the Alerts team, and I believe this particular change was made for load reasons on the backing services.  Feature requests to the API should be channeled through support.  If that's something you would like to see changed, please open a support case to make the request.

**Comment by gambrell** [comment]
I see that the New Relic UI is now following suit for NRQL alert conditions. I ran a test and found that after the timeout the alert is closed as expected.  After the 5 minutes defined in the alert condition plus 3 minutes for the evaluation offset, the alert was opened again.  
Documentation here: https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-violations/how-alert-condition-violations-are-closed#time-limit

**Comment by zlesnr** [comment]
Poof, that's great.  Thanks for the update too, since now I know how it works.
