### ISSUE TITLE
Avoid recreating policy and conditions on update of `channel_ids` property

### ISSUE THREAD

**Issue by dvishniakov** [newrelic/terraform-provider-newrelic#946]
- [ ] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [ ] A list of [affected resources](#affected-resources) and/or data sources
- [ ] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [ ] Description of the [current behavior](#actual-behavior) (the bug)
- [ ] Description of the [expected behavior](#expected-behavior)
- [ ] Any related [log output](#debug-output)

### Versions
Terraform 0.13.1
Newrelic: tried 2.7 to 2.10

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_alert_policy`  https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_policy

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
resource "newrelic_alert_policy" "test" {
  incident_preference = "PER_CONDITION"
  name                = local.title
  channel_ids         = var.extra_notification_channels
}
```

### Actual Behavior
Whenever I change `var.extra_notification_channels`, Terraform wants to recreate all alert conditions of the policy.
Even though there is a note in the resource description that policy is recreated there is no explanation why that is happening. When I try to modify the policy via UI the policy and alert conditions are not recreated and the policy ID stays the same allowing all saved links to work properly.

Also I've noticed that modifying notification channels via UI is not visible to terraform provider. It just shows no infra changes to me when I actually did them.

### Expected Behavior
Alert policy should be modified in place, alert conditions should not be modified.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by ctrombley** [comment]
@dvishniakov Can I suggest a workaround in the meantime?  Replacing the `channel_ids` argument with once or more instances of the `newrelic_alert_policy_channel` resource should have the intended effect.

As far as the notification channels, if you are updating any secret values in the UI, it is a known limitation that the provider will not be able to notice a change.  This is because the underlying API does not pass back the secrets that have been provisioned during the initial create.  There is a body of work being considered to move notification channels to our NerdGraph API where we will be able to make some changes that will address this limitation in a more reasonable manner, but that work has not been committed to yet by any team.

**Comment by sanderblue** [comment]
@dvishniakov Also please note the `newrelic_alert_policy` [docs for `channel_ids` ](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_policy#channel_ids) state that changing the IDs in `channel_ids` will result in a _**new**_ alert policy being created and the old one being deleted. 

Since alert conditions are attached to alert policies, the alert conditions must also be updated with the new policy ID reference. This is Terraform core ensuring dependent resources are updated accordingly. This is why you're seeing this behavior.

As Chris mentioned, since this is not the desired behavior for your scenario, please use [`newrelic_alert_policy_channel`](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_policy_channel) resource instead.
